display_images_shell('mass_orientation_images', 146, 1, ...
    'line_dir', 'C:\isbe\asymmetry_project\data\line_maps\2004_screening\mass_roi\',...
    'orientation_dir', 'C:\isbe\asymmetry_project\data\orientation_maps\2004_screening\mass_roi\',...
    'line_thresh', 0.6,...
    'spacing', 4);
display_images_shell('mass_orientation_images', 146, 1, ...
    'orientation_dir', 'C:\isbe\asymmetry_project\data\orientation_maps\2004_screening\mass_roi\',...
    'line_thresh', 0.6,...
    'spacing', 4);
display_images_shell('mass_orientation_images', 146, 1, ...
    'line_dir', 'C:\isbe\asymmetry_project\data\line_maps\2004_screening\mass_roi\',...
    'line_thresh', 0.6,...
    'spacing', 4);
display_images_shell('mass_orientation_images', 146, 1, ...
    'line_thresh', 0.6,...
    'spacing', 4);
display_images_shell('test_orientation_images4', 100, 1);
%%
display_images_shell('mass_orientation_images', 146, 1, ...
    'line_dir', 'C:\isbe\asymmetry_project\data\line_maps_g2\2004_screening_processed\old_data\mass_roi\',...
    'orientation_dir', 'C:\isbe\asymmetry_project\data\orientation_maps_g2\2004_screening_processed\old_data\mass_roi\',...
    'line_thresh', 0.6,...
    'spacing', 2);