%lets try and find some nipples using the radial maps

mam_list = dir('C:\isbe\asymmetry_project\data\mammograms\2004_screening\abnormals\*.mat');
seg_list = dir('C:\isbe\asymmetry_project\data\segmentations\2004_screening\abnormals\*.mat');
rad_list = dir('C:\isbe\asymmetry_project\data\weighted_radial_maps\2004_screening\abnormals\*inf.mat');
breast_names = get_mammo_info(mam_list);
%%
sigma = 8;
norm_width = 100;
for ii = 9*10+(1:10)
    
    %Load radial map and smooth
    rad_map = u_load(['C:\isbe\asymmetry_project\data\weighted_radial_maps\2004_screening\abnormals\' rad_list(ii).name]);
    rad_map = imfilter(rad_map, fspecial('gaussian', 6*sigma+1, sigma));
    
    %Load segmentation and resize
    seg = u_load(['C:\isbe\asymmetry_project\data\segmentations\2004_screening\abnormals\' seg_list(ii).name]);
    [breast_border air_idx] = segment_breast_resize(size(rad_map), seg);
    
    len = length(air_idx);
    normal_p = zeros(len, norm_width);
    normal_x = zeros(len, norm_width);
    normal_y = zeros(len, norm_width);

    %Compute the normal vectors at each point on the inner border
    [fx, fy] = gradient(breast_border(air_idx,:));

    %normalise fy
    fy = fy ./ [sqrt(sum(fy.^2, 2)), sqrt(sum(fy.^2, 2))];

    %Compute normal profiles of the image at every point
    for jj = 1:len %= number of rows in skin_air

        if strcmpi(breast_names{ii}(4), 'L')
            n1_x = breast_border(air_idx(jj), 1) - norm_width*fy(jj, 2);
            n1_y = breast_border(air_idx(jj), 2) + norm_width*fy(jj, 1);
        else
            n1_x = breast_border(air_idx(jj), 1) + norm_width*fy(jj, 2);
            n1_y = breast_border(air_idx(jj), 2) - norm_width*fy(jj, 1);
        end
        n2_x = breast_border(air_idx(jj), 1) + 0*fy(ii, 2);
        n2_y = breast_border(air_idx(jj), 2) - 0*fy(ii, 1);

        [cx, cy, cp] = improfile(rad_map, [n1_x, n2_x], [n1_y, n2_y], norm_width);
        normal_p(jj, :) = cp';
        normal_x(jj, :) = cx';
        normal_y(jj, :) = cy';

    end

    %Get sample points from breast air border
    %sample_pts = sub2ind(size(rad_map), round(breast_border(air_idx,2)), round(breast_border(air_idx,1)));
    
    %Get maximum idx of rad map at breast air border
    %[m max_idx] = max(rad_map(sample_pts));
    %[m max_idx] = max(nansum(normal_p,2));
    normal_p(isnan(normal_p)) = 0;
    normal_p = sort(normal_p, 2, 'descend');
    [m max_idx] = max(mean(normal_p(:,1:50),2));
    
    %Get precited nipple in rad map
    rad_nipple = breast_border(air_idx(max_idx),:);
    
    %Plot nipple position on rad map and mammogram
    mammo = u_load(['C:\isbe\asymmetry_project\data\mammograms\2004_screening\abnormals\' mam_list(ii).name]);
    
    figure;
    subplot(1,2,1); imagesc(rad_map); axis image; colormap(jet(256)); hold on;
    plot(rad_nipple(:,1), rad_nipple(:,2), 'k*');
    plot(breast_border(air_idx,1), breast_border(air_idx,2),'k');
    plot(normal_x', normal_y', 'w');
    subplot(1,2,2); imagesc(mammo); axis image; colormap(jet(256)); hold on;
    plot(2*rad_nipple(:,1), 2*rad_nipple(:,2), 'k*');
end
%%
m_list = dir('C:\isbe\asymmetry_project\data\mass_masks\2004_screening\normals\*.mat');
num_samples = 0;
for ii = 1:length(m_list)
    mask = u_load(['C:\isbe\asymmetry_project\data\mass_masks\2004_screening\normals\', m_list(ii).name]);
    num_samples = num_samples + sum(mask(:));
end
%%
save_radial_data(...
    'save_path', 'C:\isbe\asymmetry_project\data\radial_samples\2004_screening\abnormals\wr1',...
    'mask_dir', 'C:\isbe\asymmetry_project\data\mass_masks\2004_screening\abnormals\',...
    'radial_dir','C:\isbe\asymmetry_project\data\weighted_radial_maps\2004_screening\abnormals\',...
    'template_dir', 'C:\isbe\asymmetry_project\data\template_maps\2004_screening\abnormals\', ...
    'samples_per_image', [],...
    'dist_range', [16 32 64],...
    'sigma_range', [4 8],...
    'angular_res', 1,...
    'mammo_list', [], ...
    'quiet', 1);
%%
save_radial_data(...
    'save_path', 'C:\isbe\asymmetry_project\data\radial_samples\2004_screening\normals\wr3',...
    'mask_dir', 'C:\isbe\asymmetry_project\data\mass_masks\2004_screening\normals\',...
    'radial_dir','C:\isbe\asymmetry_project\data\weighted_radial_maps\2004_screening\normals\',...
    'template_dir', 'C:\isbe\asymmetry_project\data\template_maps\2004_screening\normals\', ...
    'samples_per_image', [],...
    'dist_range', [16 32 64 128 256],...
    'sigma_range', [1 2 4 8],...
    'angular_res', 1,...
    'mammo_list', [], ...
    'quiet', 1);
%%
save_mass_training_data(...
    'save_name', 'wr1',...
    'save_dir', 'C:\isbe\asymmetry_project\data\radial_samples\',...
    'abnormal_data', '2004_screening\abnormals',...
    'normal_data', '2004_screening\normals',... 
    'image_dir', 'C:\isbe\asymmetry_project\data\mammograms\',... 
    'mask_dir', 'C:\isbe\asymmetry_project\data\mass_masks\',...
    'radial_dir', 'C:\isbe\asymmetry_project\data\weighted_radial_maps\',...
    'template_dir', 'C:\isbe\asymmetry_project\data\template_maps\',...
    'dist_range', [16 32 64 128 256],...
    'sigma_range', [1 2 4 8],...
    'angular_res', 1);
%%
save_mass_training_data(...
    'save_name', 'radial',...
    'save_dir', 'C:\isbe\asymmetry_project\data\radial_samples\',...
    'abnormal_data', '2004_screening\abnormals',...
    'normal_data', '2004_screening\normals',... 
    'image_dir', 'C:\isbe\asymmetry_project\data\mammograms\',...
    'mask_dir', 'C:\isbe\asymmetry_project\data\mass_masks\',...
    'radial_dir', 'C:\isbe\asymmetry_project\data\radial_maps\',...
    'template_dir', 'C:\isbe\asymmetry_project\data\template_maps\',...
    'dist_range', [16 32 64 128 256],...
    'sigma_range', [1 2 4 8],...
    'angular_res', 1);
%%
[abnormal_data] = load_mass_feature_data(...
    'num_samples', 2e3,... % the mandatory arguments
    'mammo_idx', 16:146,...
    'samples_path', 'C:\isbe\asymmetry_project\data\radial_samples\2004_screening\abnormals\wr1',...
    'do_template', 0,...
    'do_scale', 0,...
    'dist_range', [16 32 64 128 256],...
    'sigma_range', [1 2 4 8],...
    'angular_res', 1,...
    'quiet', 1,...
    'save_path', []);
%%
sampling_method_args.abnormal_data  = '2004_screening/abnormals';  
sampling_method_args.normal_data  = '2004_screening/normals'; 
sampling_method_args.image_dir = [asymmetryroot, 'data/mammograms2/'];
sampling_method_args.save_dir = [asymmetryroot, 'data/radial_samples/'];
sampling_method_args.save_name = 'wr2';
sampling_method_args.fold_id = 1;
sampling_method_args.num_folds = 10;
sampling_method_args.view = [];
sampling_method_args.dist_range = [16 32];
sampling_method_args.sigma_range = [1 2];
sampling_method_args.angular_res = 12;
sampling_method_args.image_type = '.mat';
sampling_method_args.num_samples = 2e3;

[training_data training_labels] = load_mass_training_data(sampling_method_args);
%%
m_list = dir([asymmetryroot 'data/mammograms2/2004_screening/normals/*.mat']);
save_radial_data(...
    'save_path', [asymmetryroot 'data/radial_samples/2004_screening/normals/wr3'],...
    'mask_dir', [asymmetryroot 'data/mass_masks/2004_screening/normals/'],...
    'radial_dir', [asymmetryroot 'data/weighted_radial_maps/2004_screening/normals/'],...
    'template_dir', [asymmetryroot 'data/template_maps/2004_screening/normals/'], ...
    'samples_per_image', [],...
    'dist_range', [16 32 64 128 256],...
    'sigma_range', [1 2 4 8],...
    'angular_res', 1,...
    'mammo_list', m_list(1:146), ...
    'quiet', 1);
%%
m_list1 = dir('C:\isbe\asymmetry_project\data\mammograms\2004_screening\abnormals\results\wr1\*mat');
m_list2 = dir('C:\isbe\asymmetry_project\data\mammograms\2004_screening\abnormals\results\wr2\*mat');
for ii = 1:length(m_list1)
    map1 = load(['C:\isbe\asymmetry_project\data\mass_maps\wr1ts\2004_screening\abnormals\' m_list1(ii).name]);
    map2 = load(['Z:\asymmetry_project\data\mammograms\2004_screening\abnormals\results\wr3\' m_list1(ii).name]);
    
    figure; 
    subplot(1,2,1); imagesc(imfilter(map1.out_var, fspecial('gaussian', 7, 1))); axis image; colormap(jet(256));
    subplot(1,2,2); imagesc(imfilter(map2.out_var, fspecial('gaussian', 7, 1))); axis image; colormap(jet(256));
end
%%
load('C:\isbe\asymmetry_project\data\radial_rfs\wr2_01\sampling_args.mat');
for ii = 2:10
    load(['Z:\asymmetry_project\data\radial_rfs\wr2_' zerostr(ii,2) '\random_forest.mat']);
    random_forest.tree_root = 'C:\isbe\asymmetry_project\data\radial_rfs\';
    save(['C:\isbe\asymmetry_project\data\radial_rfs\wr2_' zerostr(ii,2) '\random_forest.mat'], 'random_forest');
    save(['C:\isbe\asymmetry_project\data\radial_rfs\wr2_' zerostr(ii,2) '\sampling_args.mat'], 'sampling_method_args');
end
%%
for ii = 1:10
    %load(['Z:\asymmetry_project\data\radial_rfs\wr2_' zerostr(ii,2)
    %'\random_forest.mat']);
    save(['Z:\asymmetry_project\data\radial_rfs\wr2_' zerostr(ii,2) '\sampling_args.mat'], 'sampling_method_args');
end
%%
classify_mammo_fold('custom_id', 'wr2', 'num_jobs', 1, 'fold_id', 1, ...
        'classify_abnormals', 0, 'classify_normals', 1, 'classify_contra', 1, 'mammo_rf_dir', 'radial_rfs');
for ii = 2:10
    classify_mammo_fold('custom_id', 'wr2', 'num_jobs', 1, 'fold_id', ii, ...
        'classify_abnormals', 1, 'classify_normals', 1, 'classify_contra', 1, 'mammo_rf_dir', 'radial_rfs');
end