sample_testing_image_multibars(...
    'num_images', 10, ... % the mandatory arguments
    'spicule', 0, ...
    'bg_dir', 'C:\isbe\dev\classification\data\normal_smooth512\',...
    'width_range', [4 16],...
    'orientation_range', [0 180],...
    'contrast_range', [2 16],...
    'max_numlines', 20,...
    'save_path', [],...
    'plot', 1);

%%
tic;
sample_testing_image_multibars_mb(...
    'num_images', 10, ... % the mandatory arguments
    'bg_dir', 'C:\isbe\dev\classification\data\normal_smooth512\',...
    'width_range', [4 16],...
    'orientation_range', [0 180],...
    'contrast_range', [2 16],...
    'max_numlines', 20,...
    'save_path', [],...
    'plot', 1);
toc;