

amb_automodelbuild (reshape_MDL(shapes_u), 'circle', 'nIterations', 10,...
    'saveFrequency', 50, 'Quiet', 1,...
    'optimisePose', 1, 'optimiseOrigin', 1, 'nExamplesToOptimise', 101,...
    'initialAlign', 0, 'initialOriginOptimisation', 0,...
    'nSamplePoints', 500, 'totalMaxFevals', 1e5, 'saveDirName', del_me,...
    'optimiseParameterisation', 0,...
    'poseOptimisationsPerIteration', 1,...
    'originOptimisationsPerIteration', 1);

%%
figure; axis equal; hold on;
for ii = 1:101
    plot(reparameterisedPoints(1,:,ii), reparameterisedPoints(2,:,ii));
    plot(reparameterisedPoints(1,1,ii), reparameterisedPoints(2,1,ii), 'rx');
end
    