generate_line_training_data(... % the user's input
    'num_samples', 2e3, ...
    'bg_dir', 'C:\isbe\asymmetry_project\data\synthetic_backgrounds\smooth512\train\',...
    'decomp_type', 'dt',...
    'num_bgs', [],...
    'bg_stem', [],...
    'bg_zeros', [],...
    'detection_type', 'detection',...
    'pts_per_image', 500,...
    'bg_ratio', 1,...
    'width_range', [4 16],...
    'orientation_range', [0 360],...
    'contrast_range', [4 16],...
    'decay_rate', 4,...
    'line_type', 'sin',...
    'num_levels', 5,...
    'feature_shape', 'rect',...
    'feature_type', 'all',...
    'do_max', 0,...
    'rotate', 0,...
    'win_size', 3,...
    'num_angles', 8,...
    'min_wavelength', 4,...
    'onf', 0.65,...
    'pca', [],...
    'use_nag', 1,...
    'save_path', [], ...
    'plot', 0);
%%
generate_line_training_data(... % the user's input
    'num_samples', 2e3, ...
    'bg_dir', 'C:\isbe\asymmetry_project\data\synthetic_backgrounds\smooth512\train\',...
    'decomp_type', 'mono',...
    'num_bgs', [],...
    'bg_stem', [],...
    'bg_zeros', [],...
    'detection_type', 'detection',...
    'pts_per_image', 500,...
    'bg_ratio', 1,...
    'width_range', [4 16],...
    'orientation_range', [0 360],...
    'contrast_range', [4 16],...
    'decay_rate', 4,...
    'line_type', 'sin',...
    'num_levels', 5,...
    'feature_shape', 'rect',...
    'feature_type', 'all',...
    'do_max', 0,...
    'rotate', 0,...
    'win_size', 3,...
    'num_angles', 8,...
    'min_wavelength', 4,...
    'onf', 0.65,...
    'pca', [],...
    'use_nag', 1,...
    'save_path', [], ...
    'plot', 0);
%%
generate_line_training_data(... % the user's input
    'num_samples', 2e3, ...
    'bg_dir', 'C:\isbe\asymmetry_project\data\synthetic_backgrounds\smooth512\train\',...
    'decomp_type', 'linop',...
    'num_bgs', [],...
    'bg_stem', [],...
    'bg_zeros', [],...
    'detection_type', 'detection',...
    'pts_per_image', 500,...
    'bg_ratio', 1,...
    'width_range', [4 16],...
    'orientation_range', [0 360],...
    'contrast_range', [4 16],...
    'decay_rate', 4,...
    'line_type', 'sin',...
    'num_levels', 5,...
    'feature_shape', 'rect',...
    'feature_type', 'all',...
    'do_max', 0,...
    'rotate', 1,...
    'win_size', 1,...
    'num_angles', 8,...
    'min_wavelength', 4,...
    'onf', 0.65,...
    'pca', [],...
    'use_nag', 1,...
    'save_path', [], ...
    'plot', 0);
%%
generate_line_training_data(... % the user's input
    'num_samples', 2e3, ...
    'bg_dir', 'C:\isbe\asymmetry_project\data\synthetic_backgrounds\smooth512\train\',...
    'decomp_type', 'pixel',...
    'num_bgs', [],...
    'bg_stem', [],...
    'bg_zeros', [],...
    'detection_type', 'detection',...
    'pts_per_image', 500,...
    'bg_ratio', 1,...
    'width_range', [4 16],...
    'orientation_range', [0 360],...
    'contrast_range', [4 16],...
    'decay_rate', 4,...
    'line_type', 'sin',...
    'num_levels', 5,...
    'feature_shape', 'rect',...
    'feature_type', 'all',...
    'do_max', 0,...
    'rotate', 0,...
    'win_size', 15,...
    'num_angles', 8,...
    'min_wavelength', 4,...
    'onf', 0.65,...
    'pca', [],...
    'use_nag', 1,...
    'save_path', [], ...
    'plot', 0);
%%
load('C:\isbe\asymmetry_project\data\synthetic_lines\lines512\image001.mat');
classify_image(... % the user's input
    'image_in', test_image,... % the mandatory arguments
    'forest', 0,...
    'decomp_type', 'pixel',...
    'forest_type', 'isbe',...
    'use_probs', 0,...
    'mask', [],...
    'num_trees', [],...
    'max_size', 128,...
    'num_levels', 5,...
    'feature_shape', 'rect',...
    'feature_type', 'all',...
    'do_max', 0,...
    'rotate', 0,...
    'win_size', 3,...
    'num_angles', 8,...
    'min_wavelength', 4,...
    'onf', 0.65,...
    'pca', [],...
    'use_nag', 0);
%%
