im_names = {'002wellcome_L4_mosaic', '035wellcome_R2_mosaic', '051wellcome_L4_mosaic'};
im_dirs = {'002wellcome\2015_02_27\L4_11_00_04', '035wellcome\2015_03_23\R2_12_24_58', '051wellcome\2015_07_10\L4_10_09_02'};
%%
for i_im = 1:3
    sequence_name = ['N:\Nailfold Capillaroscopy\camera_capture\wellcome_nailfold_study\' im_dirs{i_im} '\'];
    register_sequence(... % the user's input
        'sequence',                 [],...
        'sequence_data_path',       [sequence_name 'sequence_frames_data.dat'],...
        'sequence_dir',             sequence_name,...
        'selected_segments',        [],...[3 6 7 11 14]
        'dirt_image',               [],...
        'pixels_per_mm',            1000,...
        'min_stationary_frames',    120,...
        'mosaic_lims_x',            -310:309,...
        'mosaic_lims_y',            -230:229,...
        'frame_h',                  480,...
        'frame_w',                  640,...
        'sigma',                    6,...
        'intra_segment_offset',     120,...
        'inter_segment_offset',     240,...
        'plot',                     1,...
        'debug',                    0);
end
%%
for i_im = 1:3
    load(['N:\Nailfold Capillaroscopy\camera_capture\wellcome_nailfold_study\' im_dirs{i_im} '\segments\segment_data.mat']);
    glims = [min(segment_mosaic(segment_mask)) max(segment_mosaic(segment_mask))];
    segment_mosaic2 = imresize(segment_mosaic, 0.5, 'lanczos2');
    mask = 255*~isnan(segment_mosaic2);
    imwrite(mask, ['C:\isbe\nailfold\data\wellcome_study\fov_masks_cxx\' im_names{i_im} '_f_mask.png']);
    
    segment_mosaic2 = 128 + 127*(segment_mosaic2-glims(1))/(glims(2)-glims(1));
    segment_mosaic2(isnan(segment_mosaic2)) = 255;
    imwrite(uint8(segment_mosaic2),...
        ['C:\isbe\nailfold\data\wellcome_study\images_png\' im_names{i_im} '.png']);
    
end
%%
nailfold = imread('C:\isbe\nailfold\data\wellcome_study\images_png\002wellcome_L4_mosaic.png');
mask = imread('C:\isbe\nailfold\data\wellcome_study\fov_masks_cxx\002wellcome_L4_mosaic_f_mask.png') > 0;
detect_capillaries(nailfold, 1, 'nailfold_mask', mask, ...
    'save_path', 'C:\isbe\nailfold\data\wellcome_study\detected_capillaries_cxx\002wellcome_L4_mosaic_caps.mat');
%%
for i_im = 1:3
    mask = imread(['C:\isbe\nailfold\data\wellcome_study\fov_masks_cxx\' im_names{i_im} '_f_mask.png']) > 0;   
    nailfold = imread(['C:\isbe\nailfold\data\wellcome_study\images_png\' im_names{i_im} '.png']);
    detect_capillaries(nailfold, 1:7, 'nailfold_mask', mask, ...
        'save_path', ['C:\isbe\nailfold\data\wellcome_study\detected_capillaries_cxx\' im_names{i_im} '_caps.mat']);
end
%%
for i_im = 2%1:3
    display_automated_markup(... % non-strict mode
        'image_names',          im_names(i_im),...
        'data_dir',             'C:\isbe\nailfold\data\wellcome_study\',...
        'image_dir',            'images_png',...
        'caps_dir',             'detected_capillaries_cxx',...
        'image_type',           '.png',...
        'um_per_pix',           1.25,...
        'aam_thresh',           inf,...
        'plot_nondistal',       1,...
        'plot_rejected',        0,...
        'plot_r',               1,...
        'plot_c',               1,...
        'plot_view',            [],...
        'plot_caxis',           []); 
end
%%
sequence_name = ['N:\Nailfold Capillaroscopy\camera_capture\wellcome_nailfold_study\' im_dirs{2} '\'...
    'sequence_frames_data.dat'];
sequence = load(sequence_name);
[segments_s, segments_ns, motor_x, motor_y, motor_z, sharpness] = ...
    get_stationary_segments(sequence, 120);
plot_segment_traces(1000, segments_s, segments_ns, motor_x, motor_y, motor_z);
%%
basename = 'C:\isbe\MondayMeeting5thOct\figs\segments\seg_frame';
for i_s = 1:size(segment_frames,3)
    write_im_from_colormap(segment_frames(:,:,i_s),...
        [basename zerostr(i_s,2) '.png'], gray(256));
end
%%
tic;
sequence_name = ['N:\Nailfold Capillaroscopy\camera_capture\wellcome_nailfold_study\' im_dirs{2} '\'];
    register_sequence(... % the user's input
        'sequence',                 [],...
        'sequence_data_path',       [sequence_name 'sequence_frames_data.dat'],...
        'sequence_dir',             sequence_name,...
        'selected_segments',        7,...[3 6 7 11 14]
        'dirt_image',               s.dirt_image,...
        'pixels_per_mm',            1000,...
        'min_stationary_frames',    120,...
        'mosaic_lims_x',            -310:309,...
        'mosaic_lims_y',            -230:229,...
        'frame_h',                  480,...
        'frame_w',                  640,...
        'sigma',                    6,...
        'intra_segment_offset',     120,...
        'inter_segment_offset',     240,...
        'delete_frames',            0,...
        'plot',                     1,...
        'debug',                    0,...
        'overwrite',                0);
    toc;
%%
v = load('C:\isbe\nailfold\data\wellcome_study\detected_capillaries_cxx\035wellcome_R2_mosaic_caps.mat');
s = load('N:\Nailfold Capillaroscopy\camera_capture\wellcome_nailfold_study\035wellcome\2015_03_23\R2_12_24_58\segments\segment_data.mat');

i_seg = 7;
frame_dir = ['N:\Nailfold Capillaroscopy\camera_capture\wellcome_nailfold_study\035wellcome\2015_03_23\R2_12_24_58\registered' zerostr(i_seg,2) '\'];
segment_vessel_videos(i_seg, s, v, frame_dir, 0, 0);
compute_vessel_flow(i_seg, s, v, 1/1.6077, frame_dir);
%%
%im_names = {'002wellcome_L4_mosaic', '035wellcome_R2_mosaic', '051wellcome_L4_mosaic'};
im_dirs = {
    '018wellcome\2015_03_17\L2_14_14_56\'
    '018wellcome\2015_03_17\L5_14_27_10\'
    '018wellcome\2015_03_17\R2_13_53_49\'
    '038wellcome\2015_03_24\L5_14_13_54\'
    '038wellcome\2015_03_24\R3_13_48_25\'
    '065wellcome\2015_04_14\R4_11_43_06\'
    '065wellcome\2015_04_14\L1_11_48_15\'
    };

im_names = {
    '018wellcome_L2_14_14_56_mosaic'
    '018wellcome_L5_14_27_10_mosaic'
    '018wellcome_R2_13_53_49_mosaic'
    '038wellcome_L5_14_13_54_mosaic'
    '038wellcome_R3_13_48_25_mosaic'
    '065wellcome_R4_11_43_06_mosaic'
    '065wellcome_L1_11_48_15_mosaic'
    };
%
for i_im = 1:7
    sequence_name = ['N:\Nailfold Capillaroscopy\camera_capture\wellcome_nailfold_study\' im_dirs{i_im} '\'];
    register_sequence(... % the user's input
        'sequence',                 [],...
        'sequence_data_path',       [sequence_name 'sequence_frames_data.dat'],...
        'sequence_dir',             sequence_name,...
        'selected_segments',        [],...[3 6 7 11 14]
        'dirt_image',               [],...
        'pixels_per_mm',            1000,...
        'min_stationary_frames',    120,...
        'mosaic_lims_x',            -310:309,...
        'mosaic_lims_y',            -230:229,...
        'frame_h',                  480,...
        'frame_w',                  640,...
        'sigma',                    6,...
        'intra_segment_offset',     120,...
        'inter_segment_offset',     240,...
        'plot',                     1,...
        'debug',                    0);
end
%%

for i_im = 1:7
    load(['N:\Nailfold Capillaroscopy\camera_capture\wellcome_nailfold_study\' im_dirs{i_im} '\segments\segment_data.mat']);
    glims = [min(segment_mosaic(segment_mask)) max(segment_mosaic(segment_mask))];
    write_im_from_colormap(segment_mosaic, ['C:\isbe\nailfold\data\wellcome_study\images_display\' im_names{i_im} '.png'],...
        gray(256), glims, [255 255 255]);
    
end
%%
sequence_name = 'N:\Nailfold Capillaroscopy\camera_capture\wellcome_nailfold_study\009wellcome\2015_03_11\L2_13_36_42\';
    register_sequence(... % the user's input
        'sequence',                 [],...
        'sequence_data_path',       [sequence_name 'sequence_frames_data.dat'],...
        'sequence_dir',             sequence_name,...
        'selected_segments',        [],...[3 6 7 11 14]
        'dirt_image',               [],...
        'pixels_per_mm',            1000,...
        'min_stationary_frames',    120,...
        'mosaic_lims_x',            -310:309,...
        'mosaic_lims_y',            -230:229,...
        'frame_h',                  480,...
        'frame_w',                  640,...
        'sigma',                    6,...
        'intra_segment_offset',     120,...
        'inter_segment_offset',     240,...
        'plot',                     1,...
        'debug',                    0);