load('C:\isbe\nailfold\data\rsa_study\data_lists\miccai_lists.mat');
load('C:\isbe\nailfold\data\rsa_study\data_lists\image_id_data.mat');
run_ncm_batch('rsa_study/master_set', 1,... % the user's input
    'im_names',             image_id_data.im_names,...
    'im_idx',               miccai_selection.test,...
    'maxima_name',          'miccai_maxima',...
    'prob_dir',             'rf_classification/675753/',... 296655
    'ori_dir',              'rf_regression/675752/',...
    'width_dir',            'rf_regression/675754/',...
    'fov_mask_dir',         'fov_masks/',...
    'centre_dir',           'vessel_centres/w1/');
%%
load('C:\isbe\nailfold\data\rsa_study\data_lists\miccai_lists.mat');
load('C:\isbe\nailfold\data\rsa_study\data_lists\image_id_data.mat');
run_ncm_batch('rsa_study/master_set', 2:6,... % the user's input
    'im_names',             image_id_data.im_names,...
    'im_idx',               miccai_selection.test,...
    'maxima_name',          'miccai_maxima',...
    'prob_dir',             'rf_classification/675753/',... 296655
    'ori_dir',              'rf_regression/675752/',...
    'width_dir',            'rf_regression/675754/',...
    'fov_mask_dir',         'fov_masks/',...
    'centre_dir',           'vessel_centres/w1/',...
    'apex_map_dir',         'apex_maps/gh2d_w1',...
    'candidates_dir',       'miccai_maxima',...
    'hog_dir',              'hogs',...
    'rescore_dir',          'rescores',...
    'displacement_dir',     'displacements',...
    'selected_dir',         'selected_apexes',...
    'metrics_dir',          'apex_metrics',...
    'aam_dir',              'aam',...
    'feature_im_dir',       'images',...
    'save_dir',             'results',....
    'model_dir',            [nailfoldroot 'data/rsa_study/models/apex_templates/'],...
    'apex_class_rf',        [nailfoldroot 'models/apex/rescoring/miccai_all/rf.mat'],...        
    'class_map',            [nailfoldroot,'models/apex/final_MAP/miccai_class_MAP/class_map.mat'],...
    'aam_name',             'aam/orig/2/vessel_apex_orig.smd',...
    'xls_filename',         'all_image_auto_measures.xls',...
    'prob_sigma',           2,...
    'ori_sigma',            0,...
    'width_sigma',          2,...
    'exclusion_zone',       20,...
    'transform_scores',     0,...
    'apex_class_thresh',    0.5,...
    'discard_pts',          0,...
    'base_width',           20,...
    'use_island_max',       0,...
    'island_thresh',        0,...
    'feature_sigma',        0,...
    'num_cells',            8,...
    'cell_sz',              8,... %Size of HoG cells in blocks
    'block_sz',             [2 2],...%Size of blocks in cells
    'num_ori_bins',         12,... %Number of bins in orientation histograms
    'norm_method',          'l1-sqrt',... %Method for local normalisation
    'block_spacing',        8,... %Separation between blocks in pixels - controls level of overlap
    'gradient_operator',    [-1 0 1],...
    'spatial_sigma',        0, ...
    'angle_wrap',           1,...
    'dist_thresh',          24^2,...
    'min_candidates',       3,...
    'initial_thresh',       0.3,...
    'grid_spacing',         8,...
    'strong_vessel_thresh', 0.8,...
    'angle_discard_thresh', 75*pi/180,...
    'do_final_cull',        1,...
    'do_post_merge',        1,...
    'merge_dist_thresh',    60,...
    'merge_connect_thresh', 0.25,...
    'merge_n_pts',          20,...
    'overwrite',            0,...
    'do_aam',               0,...
    'width_predictor',      [],...[nailfoldroot 'models/apex/width/rf.mat'],...
    'do_distal',            1,...
    'do_nondistal',         1,...
    'selected_features',    [],... %Do them all for now
    'plot_distal',          1,...
    'plot_nondistal',       1, ...
    'um_per_pix',           1.25,...
    'aam_thresh',           -2e4,...
    'plot_rejected',        1,...
    'plot_r',               1,...
    'plot_c',               1);
%%
[co_occurrence_g3] = miccai_results_cooc_fun(...
    'image_names',          image_id_data.im_names(miccai_selection.test),...
    'data_dir',             [nailfoldroot 'data/rsa_study/master_set/'],...
    'prob_dir',             'rf_classification/296655',...
    'cluster_dir',          'apex_clusters_merged',...
    'candidates_dir',       'apex_maps\g2d\miccai_maxima\rescores',...
    'selected_dir',         'apex_maps\g2d\miccai_maxima\selected_apexes',...
    'metrics_dir',          'apex_maps\g2d\miccai_maxima\apex_metrics',...
    'do_distal',            1,...
    'do_nondistal',         1,...
    'plot', 0);
%
[co_occurrence_g1] = miccai_results_cooc_fun(...
    'image_names',          image_id_data.im_names(miccai_selection.test),...
    'data_dir',             [nailfoldroot 'data/rsa_study/master_set/'],...
    'prob_dir',             'rf_classification/675753',...
    'cluster_dir',          'apex_clusters_merged',...
    'candidates_dir',       'apex_maps\gh2d_w1\miccai_maxima\rescores',...
    'selected_dir',         'apex_maps\gh2d_w1\miccai_maxima\selected_apexes',...
    'metrics_dir',          'apex_maps\gh2d_w1\miccai_maxima\apex_metrics',...
    'do_distal',            1,...
    'do_nondistal',         1,...
    'plot', 0);
%
miccai_make_results_table(co_occurrence_g3, 'C:\isbe\nailfold\g2d_w3_results.txt');
miccai_make_results_table(co_occurrence_g1, 'C:\isbe\nailfold\g2d_w1_results.txt');