load('C:\isbe\nailfold\data\wellcome_study\sequence_names.mat');
sequence_names2 = sequence_names';

capillary_data_dir = 'C:\isbe\nailfold\data\wellcome_study\capillary_data\';
flow_results_dir = 'N:\Nailfold Capillaroscopy\Wellcome\flow_results\';
flow_metrics_dir = 'N:\Nailfold Capillaroscopy\Wellcome\flow_metrics\';
flow_output_dir = 'O:\flow_project\flow_centrelines\';

%%
failures = cell(0,1);
for i_seq = 21:numel(sequence_names)
    
    if isempty(sequence_names2{i_seq})
        continue;
    end
    
    seq_dir = [sequence_names2{i_seq} '\'];%sequence_dirs{i_seq};
    seq_name = seq_dir;
    dividers = seq_name == '\';
    pos = find(dividers, 4, 'last');
    seq_name(dividers) = '_';
    seq_name = seq_name(pos(1)+1:end-1);
    
    load([capillary_data_dir seq_name '_capillary_data.mat'],...
        'apex_measures');
    
    if isempty(apex_measures.distal)
        continue;
    end
    
    cap_num = find(apex_measures.distal.flow_measurable, 1);
    
    if isempty(cap_num)
        continue;
    end
    flow_ids = apex_measures.distal.flow_names{cap_num};   
    flow_name = [seq_name '_' flow_ids{1} '.mat'];
    
    if ~exist([flow_results_dir flow_name], 'file')
        continue;
    end

    display(['processing sequence ' num2str(i_seq) ': ' seq_name]);
    
    load([flow_metrics_dir flow_name]);
    load([flow_results_dir flow_name]);
    
    vessel_predictions = zeros(size(flow_metrics.vessel_pred,1), size(flow_metrics.vessel_pred,2), 3);
    vessel_predictions(:,:,1) = double(flow_metrics.vessel_pred) / 100;
    vessel_predictions(:,:,2) = rgb2complex(flow_metrics.vessel_ori,[],1);
    vessel_predictions(:,:,3) = double(flow_metrics.vessel_width);

    try
        [vessel_centre particles_x particles_y particles_p particles_d hit_sink smooth_ves] =...
            compute_flow_path(...
            ...'vessel_name', [],...
            ...'flow_data_dir',            'N:\Nailfold Capillaroscopy\wellcome\flow_data\',...
            ...'flow_results_dir',         'N:\Nailfold Capillaroscopy\wellcome\flow_results\',...
            ...'model_root',               'C:\isbe\nailfold\models\',...
            ...'rf_ori',                   ,...
            ...'rf_vessels',               ,...
            ...'rf_width',                 ,...
            ...'rf_vessels_args',          'vessel\detection\rf_classification\296655\job_args.mat',...
            'vessel_mask_thresh',       0.25,...
            'vessel_flow',              flow_results.flowPyramidEst{1},...
            'vessel_predictions',       vessel_predictions,...
            'apex_xy',                  flow_metrics.apex_xy,...
            'patch_contrast_scale',     70,...
            'vessels_sigma',            2,...
            'refind_apex',              1,...
            ...'hog_class_forest_path',    'apex\classification\set12g_half_296655\rf.mat',...
            ...'hog_off_x_forest_path',    'apex\offset_x\set12g_half_296655\rf.mat',...
            ...'hog_off_y_forest_path',    'apex\offset_y\set12g_half_296655\rf.mat',...
            ...'separate_trees',           0,...
            ...'apex_class_thresh',        0.1,...
            ...'base_width',               20,...
            ...'num_cells',                8,...
            ...'cell_sz',                  8,... %Size of HoG cells in blocks
            ...'block_sz',                 [2 2],...%Size of blocks in cells
            ...'num_ori_bins',             9,... %Number of bins in orientation histograms
            ...'norm_method',              'none',... %Method for local normalisation 'none'
            ...'block_spacing',            8,... %Separation between blocks in pixels - controls level of overlap
            ...'gradient_operator',        [-1 0 1],...
            ...'spatial_sigma',            0, ...
            ...'angle_wrap',               1,...
            'd', 1,...
            'M', 200,...
            'normal_max_step_length', 4,...
            'junction_max_step_length', 25,...
            'junction_angle_spread',    2*pi/3,...
            'N', 400, ...
            'double_angle', 0,...
            'use_angle_weights', 1,...
            'plot', 0);
    catch
        display(['flow_failed for ' flow_name]);
        failures{end+1,1} = flow_name;
    end
    
    save([flow_output_dir flow_name], ...
        'vessel_centre', 'particles_x', 'particles_y', 'particles_p', 'particles_d', 'hit_sink');
end