width_at_apex(5)
%%
training_patch_at_apex(421,450);
%%
[all_rf_widths all_gt_widths profile_features model_scores] = training_patch_at_apex(1,450,0);
%%
profile_features = permute(profile_features, [2 3 1]);
profile_features = profile_features(:,:);
profile_features = profile_features';

profile_features = reshape(profile_features', 300, 450*31);

width_ratios = all_gt_widths(:) ./ all_rf_widths(:);
width_differences = all_gt_widths(:) - all_rf_widths(:);
%%
warning('off', 'ASYM:unexpectedArgument');

rf_dir = 'C:\isbe\nailfold\data\rsa_study\vessel_contours\rfs\';
rf_args.prediction_type = 'rf_regression';
rf_args.n_trees = 100;
rf_args.d = [];
rf_args.w_prior = 0;
rf_args.impure_thresh = 1.0000e-004;
rf_args.split_min = 100;
rf_args.end_cut_min = 25;
rf_args.do_ubound = 0;
rf_args.quiet = 1;
rf_args.do_circular = [];
rf_args.overwrite = 0;
rf_args.minimise_size = 0;
rf_args.split_criterion = 'ssq';
rf_args.var_criterion = 'ssq';

rf_args.sampling_args.sampling_method = 'sample_saved_training_data';
rf_args.decomposition_args = [];
%
rf_args.tree_dir = [rf_dir 'apex_width_prediction\width_ratio\trees\'];
rf_args.sampling_args.y = width_ratios(1:7e3,:);
rf_args.sampling_args.X = profile_features(1:7e3,:);
predictor = random_forest_reg_train(rf_args);
predictions = random_forest_reg_predict(predictor, profile_features(7e3+1:end,:), 0);

n_pts = size(width_ratios(7e3+1:end,:),1);
figure; plot(sort(abs(predictions-width_ratios(7e3+1:end,:))), (1:n_pts)/n_pts);
%%
test_widths = all_gt_widths(:);
rf_widths = all_rf_widths(:);
predicted_widths = predictions .* rf_widths(7e3+1:end);

figure; hold all; 
plot(sort(abs(test_widths(7e3+1:end)-predicted_widths)), (1:n_pts)/n_pts);
plot(sort(abs(test_widths(7e3+1:end)-rf_widths(7e3+1:end))), (1:n_pts)/n_pts);
%%
figure;
plot(sort(width_ratios), (1:length(width_ratios))/length(width_ratios));
%%
tic;
predict_apex_offsets_set(...
    'task_id',              3, ...
    'num_jobs',             601, ...
    'model_id',             'frog',...
    'model_root',           [nailfoldroot,'models/apex'], ...
    'model_name',           'rf',...
    'data_dir',             [nailfoldroot 'data/rsa_study/test_half'],...
    'feature_im_dir',       'predictions/detection/rf_classification/296655',...
    'centre_dir',           'vessel_centres\full_centres',...
    'apex_map_dir',         'apex_maps/pool_trees',...
    'max_size',             unixenv('MAX_SIZE', 1000),...
    'separate_trees',       0,...
    'smoothing_sigma',      2,...
    'num_cells',            8,...
    'cell_sz',              8,... %Size of HoG cells in blocks
    'block_sz',             [2 2],...%Size of blocks in cells
    'num_ori_bins',         9,... %Number of bins in orientation histograms
    'norm_method',          'none',... %Method for local normalisation
    'block_spacing',        8,... %Separation between blocks in pixels - controls level of overlap
    'gradient_operator',    [-1 0 1],...
    'spatial_sigma',        0, ...
    'angle_wrap',           1,...
    'base_width',           20,...
    'apex_class_thresh',    0.5,...
    'overwrite',            1);
pooled_time = toc;
%%
tic;
predict_apex_offsets_set(...
    'task_id',              3, ...
    'num_jobs',             601, ...
    'model_id',             'frog',...
    'model_root',           [nailfoldroot,'models/apex'], ...
    'model_name',           'rf',...
    'data_dir',             [nailfoldroot 'data/rsa_study/test_half'],...
    'feature_im_dir',       'predictions/detection/rf_classification/296655',...
    'centre_dir',           'vessel_centres\full_centres',...
    'apex_map_dir',         'apex_maps/sep_trees',...
    'max_size',             unixenv('MAX_SIZE', 1000),...
    'separate_trees',       1,...
    'smoothing_sigma',      2,...
    'num_cells',            8,...
    'cell_sz',              8,... %Size of HoG cells in blocks
    'block_sz',             [2 2],...%Size of blocks in cells
    'num_ori_bins',         9,... %Number of bins in orientation histograms
    'norm_method',          'none',... %Method for local normalisation
    'block_spacing',        8,... %Separation between blocks in pixels - controls level of overlap
    'gradient_operator',    [-1 0 1],...
    'spatial_sigma',        0, ...
    'angle_wrap',           1,...
    'base_width',           20,...
    'apex_class_thresh',    0.5,...
    'overwrite',            1);
separate_time = toc;