bg_dir = {...
    [asymmetryroot 'data\synthetic_backgrounds\smooth512\train\'],...
    [asymmetryroot 'data\synthetic_backgrounds\real512\train\']};

rand('twister', 1);
randn('state', 1);

tic;
[Xr yr] = generate_line_training_data(...
    'num_samples', 1e3,...
    'bg_dir', bg_dir{2},... % the mandatory arguments
    'decomp_type', 'g2d',...
    'num_bgs', 200,...
    'bg_stem', 'bg',...
    'bg_zeros', 5,...
    'detection_type', 'orientation',...
    'pts_per_image', 50,...
    'bg_ratio', 1,...
    'width_range', [6 6],...
    'orientation_range', [0 360],...
    'contrast_range', [8 8],...
    'decay_rate', 4,...
    'line_type', 'ellipse',...
    'normalise', 0,...
    'num_levels', 4,...
    'sigma_range', [1 2 4 8],...
    'win_size', 3,...
    'use_nag', 0);
toc;

rand('twister', 1);
randn('state', 1);
tic;
%
[Xi yi] = generate_line_training_data(...
    'num_samples', 1e3,...
    'bg_dir', bg_dir{2},... % the mandatory arguments
    'decomp_type', 'g2di',...
    'num_bgs', 200,...
    'bg_stem', 'bg',...
    'bg_zeros', 5,...
    'detection_type', 'orientation',...
    'pts_per_image', 50,...
    'bg_ratio', 1,...
    'width_range', [6 6],...
    'orientation_range', [0 360],...
    'contrast_range', [8 8],...
    'decay_rate', 4,...
    'line_type', 'ellipse',...
    'normalise', 0,...
    'num_levels', 4,...
    'sigma_range', [1 4],...
    'win_size', 3,...
    'use_nag', 0);
toc;