local_root = 'fellowship';

im_names_s = dir([nailfoldroot 'data/' local_root '/images/*.mat']);
num_ims = length(im_names_s);
im_names = cell(num_ims,1);
for i_im = 1:num_ims
    im_names{i_im} = im_names_s(i_im).name(1:end-4);
end 
%%
auto_dir = [nailfoldroot 'data/' local_root '/apex_maps\set12g_half_296655\miccai_maxima\apex_metrics\'];
markup_dir = [nailfoldroot 'data/' local_root '/auto_markup/'];

create_folder(markup_dir);

for i_im = 1:num_ims
    display(['Converting image ' num2str(i_im) ' of ' num2str(num_ims)]);
    apex_measures = u_load([auto_dir im_names{i_im} '_am.mat']);
    write_automeasures_to(apex_measures, [markup_dir im_names{i_im} '_markup.txt']);
end
%%
extract_apex_measures_set(...
                'image_names',          im_names(2:end),...
                'data_dir',             [nailfoldroot 'data/' local_root '/'],...
                'image_dir',            'images',...
                'prob_dir',             'rf_classification/296655',...
                'ori_dir',              'rf_regression/296621',...
                'width_dir',            'rf_regression/297037',...
                'candidates_dir',       ['apex_maps\set12g_half_296655\miccai_maxima\rescores'],...
                'displacements_dir',    ['apex_maps\set12g_half_296655\miccai_maxima\displacements'],...
                'selected_dir',         ['apex_maps\set12g_half_296655\miccai_maxima\selected_apexes'],...
                'metrics_dir',          ['apex_maps\set12g_half_296655\miccai_maxima\apex_metrics'],...
                'aam_dir',              'aam',...
                'do_aam',               1,...
                'model_dir',            [nailfoldroot 'data/rsa_study/models/apex_templates/'],...
                'aam_name',             'aam/orig/2/vessel_apex_orig.smd',...
                'width_predictor',      [],...[nailfoldroot 'models/apex/width/rf.mat'],...
                'prob_sigma',           2,...
                'ori_sigma',            0,...
                'width_sigma',          2,...
                'do_distal',            1,...
                'do_nondistal',         1,...
                'plot', 0);