comparing_DRIVE_g2d_csf(1, ...
    'exp_name',     unixenv('EXP_NAME', 'fred'), ...
    'image_dir',      [asymmetryroot,'data/retinograms/DRIVE/training/images/'], ...
    'vessel_mask_dir',      [asymmetryroot,'data/retinograms/DRIVE/training/vessel_masks/'], ...
    'fov_mask_dir',      [asymmetryroot,'data/retinograms/DRIVE/training/fov_masks/'], ...
    'ori_dir',      [asymmetryroot,'data/retinograms/DRIVE/training/orientations/'], ...
    'width_dir',      [asymmetryroot,'data/retinograms/DRIVE/training/width_maps/'], ...
    'selected_images', [],...
    'num_pts',      unixenv('NUM_SAMPLES', 2000), ...
    'num_trees',    unixenv('NUM_TREES', 2), ...
    'make_data',    unixenv('MAKE_DATA',1), ...
    'num_angles',   unixenv('NUM_ANGLES', 6),...
    'levels',       unixenv('LEVELS', 1),...
    'do_orientation', unixenv('DO_ORIENTATION',0), ...
    'do_detection', unixenv('DO_DETECTION',1), ...
    'do_width', unixenv('DO_WIDTH',0), ...
    'win_sizes', unixenv('WIN_SIZES',[1 3]) ...
);
%%
for idx = [81 101]
    comparing_DRIVE_experiment_csf(idx, ... % non-strict mode
        'image_dir',      [asymmetryroot,'data/retinograms/DRIVE/training/images/'], ...
        'vessel_mask_dir',      [asymmetryroot,'data/retinograms/DRIVE/training/vessel_masks/'], ...
        'fov_mask_dir',      [asymmetryroot,'data/retinograms/DRIVE/training/fov_masks/'], ...
        'ori_dir',      [asymmetryroot,'data/retinograms/DRIVE/training/orientations/'], ...
        'width_dir',      [asymmetryroot,'data/retinograms/DRIVE/training/width_maps/'], ...
        'selected_images', [],...
        'num_pts',      unixenv('NUM_SAMPLES', 2000), ...
        'num_trees',    unixenv('NUM_TREES', 2), ...
        'make_data',    unixenv('MAKE_DATA',1), ...
        'do_orientation', unixenv('DO_ORIENTATION',0), ...
        'do_detection', unixenv('DO_DETECTION',0), ...
        'do_width', unixenv('DO_WIDTH',0), ...
        'do_tests', unixenv('DO_TESTS',0), ...
        'win_sizes', unixenv('WIN_SIZES',[1 3]) ...
    );
end
%%
r1 = u_load('C:\isbe\asymmetry_project\experiments\DRIVE\comparing_representations\test\1\1\bg_responses_gh2d.mat');
r2g = u_load('C:\isbe\asymmetry_project\experiments\DRIVE\comparing_representations\test\1\bg_responses_g2da.mat');
r2h = u_load('C:\isbe\asymmetry_project\experiments\DRIVE\comparing_representations\test\1\bg_responses_h2da.mat');

r1 = reshape(r1, 2000, 9, 1, 18);
r2g = reshape(r2g, 2000, 9, 5, 6);
r2h = reshape(r2h, 2000, 9, 5, 6);

max(abs(r1(:,:,:,1:3:16) - complex(r2g(:,:,1,:),r2h(:,:,1,:))))
%%
for i_decomp = 1:2
    sqrt(3 - 2*i_decomp)
end
%%
for ii = 1:16
    display(['MAKE_DATA=1 DO_DETECTION=0 DO_WIDTH=0 DO_ORIENTATION=0 NUM_SAMPLES=100000 WIN_SIZES="[1]" LEVELS="' num2str(ii)...
        '" qsub -V -t 1-10 -l highmem matlab_code/trunk/hydra/cuc/compare_DRIVE_g2d_csf.sh']);
end
%%
%Not submitted yet!!
MAKE_DATA=0 DO_DETECTION=0 DO_WIDTH=0 DO_ORIENTATION=1 NUM_SAMPLES=100000 WIN_SIZES="[1]" NUM_ANGLES=6 LEVELS="[1:16]" EXP_NAME="scales" qsub -V -t 1-10 -l highmem matlab_code/trunk/hydra/cuc/compare_DRIVE_g2d_csf.sh 
MAKE_DATA=0 DO_DETECTION=0 DO_WIDTH=0 DO_ORIENTATION=1 NUM_SAMPLES=100000 WIN_SIZES="[3]" NUM_ANGLES=6 LEVELS="[1:16]" EXP_NAME="scales" qsub -V -t 1-10 -l vhighmem matlab_code/trunk/hydra/cuc/compare_DRIVE_g2d_csf.sh 
MAKE_DATA=0 DO_DETECTION=1 DO_WIDTH=0 DO_ORIENTATION=0 NUM_SAMPLES=100000 WIN_SIZES="[3]" NUM_ANGLES=6 LEVELS="[1:16]" EXP_NAME="scales" qsub -V -t 1-10 -l vhighmem matlab_code/trunk/hydra/cuc/compare_DRIVE_g2d_csf.sh 
MAKE_DATA=0 DO_DETECTION=1 DO_WIDTH=0 DO_ORIENTATION=0 NUM_SAMPLES=100000 WIN_SIZES="[1]" NUM_ANGLES=6 LEVELS="[1:16]" EXP_NAME="scales" qsub -V -t 1-10 -l highmem matlab_code/trunk/hydra/cuc/compare_DRIVE_g2d_csf.sh 
MAKE_DATA=0 DO_DETECTION=1 DO_WIDTH=0 DO_ORIENTATION=0 NUM_SAMPLES=100000 WIN_SIZES="[1]" NUM_ANGLES=18 LEVELS="[1 2 4 8 16]" EXP_NAME="angles" qsub -V -t 1-10 -l highmem matlab_code/trunk/hydra/cuc/compare_DRIVE_g2d_csf.sh 
MAKE_DATA=0 DO_DETECTION=0 DO_WIDTH=0 DO_ORIENTATION=1 NUM_SAMPLES=100000 WIN_SIZES="[1]" NUM_ANGLES=18 LEVELS="[1 2 4 8 16]" EXP_NAME="angles" qsub -V -t 1-10 -l highmem matlab_code/trunk/hydra/cuc/compare_DRIVE_g2d_csf.sh 
MAKE_DATA=0 DO_DETECTION=0 DO_WIDTH=0 DO_ORIENTATION=1 NUM_SAMPLES=100000 WIN_SIZES="[3]" NUM_ANGLES=18 LEVELS="[1 2 4 8 16]" EXP_NAME="angles" qsub -V -t 1-10 -l vhighmem matlab_code/trunk/hydra/cuc/compare_DRIVE_g2d_csf.sh 
MAKE_DATA=0 DO_DETECTION=1 DO_WIDTH=0 DO_ORIENTATION=0 NUM_SAMPLES=100000 WIN_SIZES="[3]" NUM_ANGLES=18 LEVELS="[1 2 4 8 16]" EXP_NAME="angles" qsub -V -t 1-10 -l vhighmem matlab_code/trunk/hydra/cuc/compare_DRIVE_g2d_csf.sh 
%--------------------
%%
DECOMP_TYPE="gabor" WIN_SIZE=3 PROBABILITY_DIR="24303/" MAKE_RESAMPLING_MAPS=0.75 MAX_N_IMAGES=10 SHIFT_IMAGES=5 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/STARE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 PROBABILITY_DIR="9162/" MAKE_RESAMPLING_MAPS=0.75 MAX_N_IMAGES=10 SHIFT_IMAGES=5 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/STARE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l highmem -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="mono" WIN_SIZE=3 PROBABILITY_DIR="12394/" MAKE_RESAMPLING_MAPS=0.75 MAX_N_IMAGES=10 SHIFT_IMAGES=5 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/STARE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l highmem -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="{'g2da','h2da'}" WIN_SIZE=3 PROBABILITY_DIR="88126/" MAKE_RESAMPLING_MAPS=0.75 MAX_N_IMAGES=10 SHIFT_IMAGES=5 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/STARE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l highmem -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 PROBABILITY_DIR="24303/" MAKE_RESAMPLING_MAPS=0.75 MAX_N_IMAGES=10 SHIFT_IMAGES=15 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/STARE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 PROBABILITY_DIR="9162/" MAKE_RESAMPLING_MAPS=0.75 MAX_N_IMAGES=10 SHIFT_IMAGES=15 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/STARE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l highmem -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="mono" WIN_SIZE=3 PROBABILITY_DIR="12394/" MAKE_RESAMPLING_MAPS=0.75 MAX_N_IMAGES=10 SHIFT_IMAGES=15 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/STARE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l highmem -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="{'g2da','h2da'}" WIN_SIZE=3 PROBABILITY_DIR="88126/" MAKE_RESAMPLING_MAPS=0.75 MAX_N_IMAGES=10 SHIFT_IMAGES=15 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/STARE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l highmem -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96335'" qsub -V -hold_jid 96335 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96336'" qsub -V -hold_jid 96336 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96337'" qsub -V -hold_jid 96337 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96338'" qsub -V -hold_jid 96338 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96339'" qsub -V -hold_jid 96339 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96340'" qsub -V -hold_jid 96340 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96341'" qsub -V -hold_jid 96341 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96342'" qsub -V -hold_jid 96342 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh

%Not submitted yet!!
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96335'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96344 -V -t 6-15 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96336'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96345 -V -t 6-15 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96337'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96346 -V -t 6-15 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96338'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96347 -V -t 6-15 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh

MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96339'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96348 -V -t 1-5 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96340'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96349 -V -t 1-5 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96341'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96350 -V -t 1-5 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96342'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96351 -V -t 1-5 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh

MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96339'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96348 -V -t 16-20 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96340'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96349 -V -t 16-20 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96341'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96350 -V -t 16-20 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'96342'" NUM_JOBS=20 IMAGE_ROOT="retinograms/STARE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -hold_jid 96351 -V -t 16-20 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
%----------------------

MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24308'" NUM_JOBS=20 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 3 -l short matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13295'" NUM_JOBS=20 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 3 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'42813'" NUM_JOBS=20 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-20 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
%%
s1 = load('C:\isbe\asymmetry_project\data\retinograms\DRIVE_clean\training\predictions\detection\rf_classification\24066\roc\roc_stats.mat');
s2 = load('C:\isbe\asymmetry_project\data\retinograms\DRIVE_clean\training\predictions\detection\rf_classification\24303\roc\roc_stats.mat');

[auc_diff, idx] = sort(s2.auc_ind - s1.auc_ind, 'descend');
pred_dir = 'C:\isbe\asymmetry_project\data\retinograms\DRIVE_clean\training\predictions\detection\rf_classification\';
for ii = 1:20
    p1 = u_load([pred_dir '24066\' zerostr(idx(ii)+20,2) '_training_pred.mat']);
    p2 = u_load([pred_dir '24303\' zerostr(idx(ii)+20,2) '_training_pred.mat']);
%     figure;
%     subplot(1,3,1); imgray(p1);
%     subplot(1,3,2); imgray(p2);
%     subplot(1,3,3); imgray(p1 - p2); colormap jet;
    figure;imgray(p1 - p2); colormap jet;
    title(['Image ' num2str(idx(ii)) ', A_z = (' num2str(s1.auc_ind(idx(ii))) ', ' num2str(s2.auc_ind(idx(ii))) ', ' num2str(auc_diff(ii)) ')']);
end
%%

predictor = build_predictor(... % the user's input
    'predictor_name',       unixenv('PREDICTOR_NAME','predictor'), ...
    'task_id',				unixenv('SGE_TASK_ID',1), ...
    'job_id',				unixenv('JOB_ID',['pc',datestr(now,'yyyymmddTHHMMSS')]), ...
    ... % Folders
    'image_root',           [asymmetryroot,'data/fibre/training'],...
    'model_root',           [asymmetryroot,'data/models/fibre'], ...
	... % Output parameters
    'output_type',          unixenv('OUTPUT_TYPE', 'orientation'), ...
	... % Sampling parameters
    'num_samples',			unixenv('NUM_SAMPLES',1000), ...
    'max_n_images',         unixenv('MAX_N_IMAGES',25), ...
    'shift_images',         unixenv('SHIFT_IMAGES',-20), ...
    'bg_ratio',				unixenv('BG_RATIO',1), ...
    'replace_sample',       unixenv('REPLACE_SAMPLE', false), ...
    'sampling_method',      unixenv('SAMPLING_METHOD','generate_training_data'), ...
    'shrink_fov',           unixenv('SHRINK_FOV',false), ...
    'image_type', 			unixenv('IMAGE_TYPE','real'), ...
        ... % Image sampling parameters
        'image_dir',            unixenv('IMAGE_DIR', 'images'),...
        'fov_mask_dir',         unixenv('FOV_MASK_DIR', 'fov_masks'),...
        'fg_mask_dir',          unixenv('FG_MASK_DIR', 'fibre_masks'),...
        'prediction_dir',       unixenv('PREDICTION_DIR', 'predictions'),...
        'probability_dir',      unixenv('PROBABILITY_DIR', '96675\'),... %
        'ori_dir',              unixenv('ORI_DIR', 'orientation_maps'),...
        'make_resampling_maps',          unixenv('MAKE_RESAMPLING_MAPS', 0.75), ...
	... % Image feature/decomposition parameters
    'num_levels', 			unixenv('NUM_LEVELS',2), ...
    'win_size',				unixenv('WIN_SIZE',3), ...
    'decomp_type', 			unixenv('DECOMP_TYPE',{'g2da', 'h2da'}), ...
        ... % DTCWT parameters
        'feature_shape', 		unixenv('FEATURE_SHAPE','rect'), ...
        'feature_type',			unixenv('FEATURE_TYPE','conj'), ...
    ... % Predictor parameters
    'prediction_type',		unixenv('PREDICTION_TYPE','rf_regression'), ...
        ... % Tree/Forest parameters
        'n_trees',				unixenv('NUM_TREES',1), ...
        'split_criterion_c',    unixenv('SPLIT_CRITERION_C','gdi'),...
        'split_criterion_r',    unixenv('SPLIT_CRITERION_R','ssq'),...
        'var_criterion_c',		unixenv('VAR_CRITERION_C','mabs'),...
        'var_criterion_r',		unixenv('VAR_CRITERION_R','ssq'),...
        'split_min',			unixenv('SPLIT_MIN',10), ...
        'end_cut_min',			unixenv('END_CUT_MIN',1), ...
        'do_ubound',			unixenv('DO_UBOUND',1), ...
        'do_circular',			unixenv('DO_CIRCULAR',[]), ...
        'w_prior',				unixenv('W_PRIOR',0), ...
        'impure_thresh',		unixenv('IMPURE_THRESH',1e-4), ...
        'minimise_size',		unixenv('MINIMIZE_TREE',0), ...
        'd',                    unixenv('d',[]), ...
        'quiet',                unixenv('QUIET', 0)...
);