[r1ts.tp r1ts.fp_a] = mass_maps_roc('2004_screening/abnormals', 'map_dir', 'mass_maps\r1ts'); 
[dummy r1ts.fp_n] = mass_maps_roc('2004_screening/normals', 'map_dir', 'mass_maps\r1ts');
save c:\isbe\asymmetry_project\experiments\radial_maps\r1ts_froc.mat r1ts;

for ii = 1:10
    for jj = 1:200
        load(['Z:\asymmetry_project\data\radial_rfs\wr1_' zerostr(ii,2) '\rf_tree0' zerostr(jj,3) '.mat'])
        trees1(jj,1) = length(tree.node);
        load(['Z:\asymmetry_project\data\radial_rfs\old\wr1_' zerostr(ii,2) '\rf_tree0' zerostr(jj,3) '.mat'])
        trees2(jj,1) = length(tree.node);
    end
    [h(ii) p(ii)]= ttest2(trees1, trees2, 0.05, 'left');
end
%%
sa_list = dir('Z:\asymmetry_project\data\radial_samples\2004_screening\abnormals\wr1*.mat');
sn_list = dir('Z:\asymmetry_project\data\radial_samples\2004_screening\normals\wr1*.mat');

for ii = 1: length(sa_list)
    copyfile(...
        ['Z:\asymmetry_project\data\radial_samples\2004_screening\abnormals\' sa_list(ii).name],...
        ['Z:\asymmetry_project\data\radial_samples\2004_screening\abnormals\wr3' sa_list(ii).name(4:end)]);
    copyfile(...
        ['Z:\asymmetry_project\data\radial_samples\2004_screening\abnormals\' sa_list(ii).name],...
        ['Z:\asymmetry_project\data\radial_samples\2004_screening\abnormals\wr4' sa_list(ii).name(4:end)]);
    copyfile(...
        ['Z:\asymmetry_project\data\radial_samples\2004_screening\normals\' sn_list(ii).name],...
        ['Z:\asymmetry_project\data\radial_samples\2004_screening\normals\wr3' sn_list(ii).name(4:end)]);
    copyfile(...
        ['Z:\asymmetry_project\data\radial_samples\2004_screening\normals\' sn_list(ii).name],...
        ['Z:\asymmetry_project\data\radial_samples\2004_screening\normals\wr4' sn_list(ii).name(4:end)]);
end
%%
for jj = 1:200
    load(['Z:\asymmetry_project\data\radial_rfs\old\wr1_01\rf_tree0' zerostr(jj,3) '.mat'])
    trees1(jj,1) = length(tree.node);
    load(['Z:\asymmetry_project\data\radial_rfs\wr3_01\rf_tree0' zerostr(jj,3) '.mat'])
    trees2(jj,1) = length(tree.node);
end
[h(ii) p(ii)]= ttest2(trees1, trees2, 0.05);
%%
mammo_list = dir('C:\isbe\asymmetry_project\data\mammograms\2004_screening\normals\*mat');
[normal_data_c] = sample_mass_feature_data2(...
    'num_samples', 2e4,...
    'mask_dir', 'C:\isbe\asymmetry_project\data\mass_masks\2004_screening\normals\',...
    'radial_dir', 'C:\isbe\asymmetry_project\data\weighted_radial_maps\2004_screening\normals\',...
    'template_dir', 'C:\isbe\asymmetry_project\data\template_maps\2004_screening\normals\', ...
    'dist_range', [16 32 64 128, 256],...
    'sigma_range', [1 2 4 8],...
    'angular_res', 1,...
    'mammo_list', mammo_list(1:146), ...
    'save_path', []);
%%
mammo_list = dir('C:\isbe\asymmetry_project\data\mammograms\2004_screening\normals\*mat');
[normal_data_z] = sample_mass_feature_data2(...
    'num_samples', 2e4,...
    'mask_dir', 'Z:\asymmetry_project\data\mass_masks\2004_screening\normals\',...
    'radial_dir', 'Z:\asymmetry_project\data\weighted_radial_maps\2004_screening\normals\',...
    'template_dir', 'Z:\asymmetry_project\data\template_maps\2004_screening\normals\', ...
    'dist_range', [16 32 64 128, 256],...
    'sigma_range', [1 2 4 8],...
    'angular_res', 1,...
    'mammo_list', mammo_list(1:146), ...
    'save_path', []);
%
mammo_list = dir('C:\isbe\asymmetry_project\data\mammograms\2004_screening\abnormals\meta\*mat');
[abnormal_data_c] = sample_mass_feature_data2(...
    'num_samples', 2e4,...
    'mask_dir', 'C:\isbe\asymmetry_project\data\mass_masks\2004_screening\abnormals\',...
    'radial_dir', 'C:\isbe\asymmetry_project\data\weighted_radial_maps\2004_screening\abnormals\',...
    'template_dir', 'C:\isbe\asymmetry_project\data\template_maps\2004_screening\abnormals\', ...
    'dist_range', [16 32 64 128, 256],...
    'sigma_range', [1 2 4 8],...
    'angular_res', 1,...
    'mammo_list', mammo_list(1:146), ...
    'save_path', []);

mammo_list = dir('C:\isbe\asymmetry_project\data\mammograms\2004_screening\abnormals\meta\*mat');
[abnormal_data_z] = sample_mass_feature_data2(...
    'num_samples', 2e4,...
    'mask_dir', 'Z:\asymmetry_project\data\mass_masks\2004_screening\abnormals\',...
    'radial_dir', 'Z:\asymmetry_project\data\weighted_radial_maps\2004_screening\abnormals\',...
    'template_dir', 'Z:\asymmetry_project\data\template_maps\2004_screening\abnormals\', ...
    'dist_range', [16 32 64 128, 256],...
    'sigma_range', [1 2 4 8],...
    'angular_res', 1,...
    'mammo_list', mammo_list(1:146), ...
    'save_path', []);
%%
[normal_data_z2] = load_mass_feature_data(...
    'num_samples', 2e4,... % the mandatory arguments
    'mammo_idx', 1:146,...
    'samples_path', 'Z:\asymmetry_project\data\radial_samples\2004_screening\normals\wr1',...
    'do_template', 1,...
    'do_scale', 1,...
    'dist_range', [16 32 64 128 256],...
    'sigma_range', [1 2 4 8],...
    'angular_res', 1,...
    'quiet', 1,...
    'save_path', []);
%%
[abnormal_data_z3] = load_mass_feature_data(...
    'num_samples', 2e4,... % the mandatory arguments
    'mammo_idx', 1:146,...
    'samples_path', 'Z:\asymmetry_project\data\radial_samples\2004_screening\abnormals\wr3',...
    'do_template', 1,...
    'do_scale', 1,...
    'dist_range', [16 32 64 128 256],...
    'sigma_range', [1 2 4 8],...
    'angular_res', 1,...
    'quiet', 1,...
    'save_path', []);
%%
wr_list_c = dir('C:\isbe\asymmetry_project\data\weighted_radial_maps2\2004_screening\normals\*.mat');
wr_list_z = dir('Z:\asymmetry_project\data\weighted_radial_maps2\2004_screening\normals\*.mat');
mismatch = false(length(wr_list_c),1);
for ii = 1:length(wr_list_c)
    mismatch(ii) = wr_list_c(ii).datenum ~= wr_list_z(ii).datenum;
end
%%
mismatch_list = wr_list_c(mismatch);
%%
for ii = 1:10
    map_c = load_uint8(['C:\isbe\asymmetry_project\data\weighted_radial_maps\2004_screening\normals\' mismatch_list(ii).name]);
    map_z = load_uint8(['Z:\asymmetry_project\data\weighted_radial_maps\2004_screening\normals\' mismatch_list(ii).name]);
    figure;
    subplot(1,2,1); imagesc(map_c); axis image; colormap(jet(256));
    subplot(1,2,2); imagesc(map_z); axis image;
end
%%
for m = 1:5
    for s = 1:3
        display(['Processing m = ' num2str(m) ' s = ' num2str(s)]);
        [weighted_radial.tp_n weighted_radial.fp_n] =...
            mass_maps_roc('2004_screening/normals', 'map_dir', 'mass_maps\wr1ts', 'sigma', 2^(s+1), 'hit_method', m, 'mask_dir', 'mass_masks');
        [weighted_radial.tp_a weighted_radial.fp_a] =...
            mass_maps_roc('2004_screening/abnormals', 'map_dir', 'mass_maps\wr1ts', 'sigma', 2^(s+1), 'hit_method', m, 'mask_dir', 'template_masks');
        save(['C:\isbe\asymmetry_project\experiments\radial_maps\froc_results\weighted_radial_froc_m' num2str(m) '_s' num2str(s) '.mat'], 'weighted_radial');
        load(['C:\isbe\asymmetry_project\experiments\radial_maps\froc_results\template_froc_m' num2str(m) '_s' num2str(s) '.mat'], 'template');
        [template.tp_n template.fp_n] =...
            mass_maps_roc('2004_screening/normals', 'map_dir', 'template_maps', 'sigma', 2^(s+1), 'hit_method', m, 'mask_dir', 'mass_masks', 'num_mammos', 146);
        [template.tp_a template.fp_a] =...
            mass_maps_roc('2004_screening/abnormals', 'map_dir', 'template_maps', 'sigma', 2^(s+1), 'hit_method', m, 'mask_dir', 'template_masks');
        save(['C:\isbe\asymmetry_project\experiments\radial_maps\froc_results\template_froc_m' num2str(m) '_s' num2str(s) '.mat'], 'template');
    end
end
%%
for m = 1:5
    for s = 1:3
        figure; hold all;
        load(['C:\isbe\asymmetry_project\experiments\radial_maps\froc_results\weighted_radial_froc_m' num2str(m) '_s' num2str(s) '.mat'], 'weighted_radial');
        plot(mean(weighted_radial.fp_a), sum(weighted_radial.tp_a) / 166, '-x');
        plot(mean(weighted_radial.fp_n), sum(weighted_radial.tp_a) / 166, '-x');
        load(['C:\isbe\asymmetry_project\experiments\radial_maps\froc_results\template_froc_m' num2str(m) '_s' num2str(s) '.mat'], 'template');
        plot(mean(template.fp_a), sum(template.tp_a) / 166, '-x');
        plot(mean(template.fp_n), sum(template.tp_a) / 166, '-x');
        axis([0 30 0 1]);
        xlabel('False positives per image')
        ylabel('Sensitivity');
        title(['FROC for TP method ' num2str(m) ', sigma = ' num2str(s)]);
        legend({...
            'Mass class: TP vs FP per abnormal', ...
            'Mass class: TP vs FP per normal', ...
            'Template map: TP vs FP per abnormal', ...
            'Template map: TP vs FP per abnormal'});
        plot([0.05 0.05], [0 1], 'k:');
        plot([5 5], [0 1], 'k:');
        set(gca, 'XScale', 'log');
        
    end
        
end
%%
froc_wr = zeros(5,3);
froc_te = zeros(5,3);
%%
for m = 1:5
    for s = 1:3
        load(['C:\isbe\asymmetry_project\experiments\radial_maps\froc_results\weighted_radial_froc_m' num2str(m) '_s' num2str(s) '.mat'], 'weighted_radial');
        froc_wr(m, s) = area_under_curve(mean(weighted_radial.fp_n), sum(weighted_radial.tp_a) / 166, 0.05, 5) / log(100);
        
        load(['C:\isbe\asymmetry_project\experiments\radial_maps\froc_results\template_froc_m' num2str(m) '_s' num2str(s) '.mat'], 'template');
        froc_te(m, s) = area_under_curve(mean(template.fp_n), sum(template.tp_a) / 166, 0.05, 5) / log(100);
    end    
end
%%
m = 4; s = 0;
[template.tp_n template.fp_n] =...
    mass_maps_roc('2004_screening/normals', 'map_dir', 'template_maps', 'sigma', s, 'hit_method', m, 'mask_dir', 'mass_masks', 'num_mammos', 146);
[template.tp_a template.fp_a] =...
    mass_maps_roc('2004_screening/abnormals', 'map_dir', 'template_maps', 'sigma', s, 'hit_method', m, 'mask_dir', 'template_masks');
save(['C:\isbe\asymmetry_project\experiments\radial_maps\froc_results\template_froc_m' num2str(m) '_s' num2str(s) '.mat'], 'template');
%%
for m = 1:5
    load(['C:\isbe\asymmetry_project\experiments\radial_maps\froc_results\template_froc_m' num2str(m) '_s1.mat'], 'template');
    for s = 3
        load(['C:\isbe\asymmetry_project\experiments\radial_maps\froc_results\weighted_radial_froc_m' num2str(m) '_s' num2str(s) '.mat'], 'weighted_radial');
        
        figure;
        
        subplot(1,2,1); hold all;
        plot(mean(weighted_radial.fp_n), sum(weighted_radial.tp_a) / 166, '-x', 'linewidth', 2);
        plot(mean(template.fp_n), sum(template.tp_a) / 166, '-x', 'linewidth', 2);
        
        axis([0 25 0 1]);
        xlabel('False positives per image')
        ylabel('Sensitivity');
        title(['FROC for TP method ' num2str(m)]);
        legend({...
            'RF classification: TP vs FP per normal', ...
            'Template matching: TP vs FP per normal'}, 'location', 'southeast');
        plot([0.05 0.05], [0 1], 'k:');
        plot([5 5], [0 1], 'k:');
        
        subplot(1,2,2); hold all;
        plot(mean(weighted_radial.fp_n), sum(weighted_radial.tp_a) / 166, '-x', 'linewidth', 2);
        plot(mean(template.fp_n), sum(template.tp_a) / 166, '-x', 'linewidth', 2);
        
        axis([0 25 0 1]);
        xlabel('False positives per image (log scale)')
        ylabel('Sensitivity');
        title(['FROC for TP method ' num2str(m)]);
        legend({...
            'RF classification: TP vs FP per normal', ...
            'Template matching: TP vs FP per normal'}, 'location', 'southeast');
        plot([0.05 0.05], [0 1], 'k:');
        plot([5 5], [0 1], 'k:');
        set(gca, 'XScale', 'log');
        
        saveas(gcf, ['C:\isbe\asymmetry_project\experiments\radial_maps\figures\froc_method' num2str(m) '.bmp']);
        
    end
        
end