cjr_batch_images2pyramids(...
    'BreastDir','C:\isbe\dev\background\images\normal_2',...
    'OutputDir','C:\isbe\dev\background\pyramid\normal_2',... % Mandatory arguments
    'Keep', 0.99, ...% Optional arguments
    'NumPyramidLevels', 5, ...
    'NumOrientations', 5, ...
    'InputImageFormat', 'bmp');

%%
data_p = get_pyramid_data_for_clustering(...
    'IdxFile', 'C:/isbe/dev/background/idx/normal_2/cluster_idx001',...
     'ImageDir', 'C:/isbe/dev/background/pyramid/normal_2/',...
     'Dimensions', 25);
 
%%
 [data] = get_window_data_for_clustering(...
     'IdxFile','C:/isbe/dev/background/idx/pectoral_2/cluster_idx001',...
     'ImageDir', 'C:/isbe/dev/background/images/pectoral_2/',...
     'Dimensions', 5);
        