errors_1 = zeros(40,1);
errors_3 = zeros(40,1);
n_trees = 5:5:200;
%%
for ii = 20:length(n_trees)-1
    display(['Processing ', num2str(ii)]);
    [ori_errors_3] = compute_image_orientation_errors(...
        'C:\isbe\asymmetry_project\data\synthetic_lines\real512',...
        ['Z:\data\synthetic_lines\real512\results\305894\' zerostr(n_trees(ii),3)]);
    errors_3(ii) = mean(abs(ori_errors_3(:,1)));
    
    [ori_errors_1] = compute_image_orientation_errors(...
        'C:\isbe\asymmetry_project\data\synthetic_lines\real512',...
        ['Z:\data\synthetic_lines\real512\results\306060\' zerostr(n_trees(ii),3)]);
    errors_1(ii) = mean(abs(ori_errors_1(:,1)));
    
end
[ori_errors_3] = compute_image_orientation_errors(...
    'C:\isbe\asymmetry_project\data\synthetic_lines\real512',...
    'Z:\data\synthetic_lines\real512\results\305894\');
errors_3(length(n_trees)) = mean(abs(ori_errors_3(:,1)));

[ori_errors_1] = compute_image_orientation_errors(...
    'C:\isbe\asymmetry_project\data\synthetic_lines\real512',...
    'Z:\data\synthetic_lines\real512\results\306060\');
errors_1(length(n_trees)) = mean(abs(ori_errors_1(:,1)));

figure; hold on;
plot(n_trees, errors_1, 'g');
plot(n_trees, errors_3, 'r');
legend('1x1 windows', '3x3 windows');
xlabel('Number of trees');
ylabel('Mean absolute error');
title('RF orientation estimation errors for increasing number of trees');
%%
display_images_shell('mass_orientation_images', 14, 1, ...
    'orientation_dir', 'C:\isbe\asymmetry_project\data\orientation_maps\rf\2004_screening\mass_roi\',...
    'line_thresh', 0.6,...
    'spacing', 4);
%%
display_images_shell('mass_orientation_images_c', 14, 1, ...
    'orientation_dir', 'C:\isbe\asymmetry_project\data\orientation_maps\rf\2004_screening\mass_roi\',...
    'line_thresh', 0.25,...
    'spacing', 4, 'quiver_length', 16);
%%
display_images_shell('mass_orientation_images_c', 14, 1, ...
    'orientation_dir', 'C:\isbe\asymmetry_project\data\orientation_maps\rf\2004_screening\mass_roi\',...
    'line_thresh', 0.0,...
    'spacing', 4, 'quiver_length', 16);
%%
display_images_shell('mass_orientation_images', 146, 1, ...
    'line_thresh', 0.6,...
    'spacing', 4);
%%
random_forest = u_load('C:\isbe\asymmetry_project\data\line_orientation_rfs\243311\random_forest.mat');
bg = u_load('C:\isbe\asymmetry_project\data\synthetic_backgrounds\real512\train\bg00001.mat');
mask = false(512);
mask(256,:) = 1;
sampling_args_c.num_levels = 4;
sampling_args_c.feature_shape = 'rect';
sampling_args_c.feature_type = 'conj';
sampling_args_c.do_max = 0;
sampling_args_c.rotate = 0;
sampling_args_c.win_size = 3;
sampling_args_c.use_nag = 0;
%
tic;
[probability_image2] = classify_image(...
    'image_in', bg,...
    'sampling_args', sampling_args_c,...
    'forest', random_forest,...
    'decomp_type', 'dt',...
    'forest_type', 'orientation',...
    'use_probs', 0,...
    'mask', mask,...
    'num_trees', 1,...
    'max_size', 512);
toc;