[roc_05, auc_05] = compute_roc_image_set_lines(...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\',...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\results\191905\', 'centre_line');
[roc_06, auc_06] = compute_roc_image_set_lines(...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\',...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\results\191906\', 'centre_line');
[roc_08, auc_08] = compute_roc_image_set_lines(...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\',...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\results\191908\', 'centre_line');
[roc_09, auc_09] = compute_roc_image_set_lines(...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\',...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\results\191909\', 'centre_line');
[roc_10, auc_10] = compute_roc_image_set_lines(...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\',...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\results\191910\', 'centre_line');
[roc_11, auc_11] = compute_roc_image_set_lines(...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\',...
    'C:\isbe\asymmetry_project\data\synthetic_lines\lines512\results\191911\', 'centre_line');
%%
num_folds = 10;
fold_id = 1;

abnormal_list = dir('C:\isbe\asymmetry_project\data\mammograms\2004_screening\abnormals\mat\*RCC*.mat');
normal_list = dir('C:\isbe\asymmetry_project\data\mammograms\2004_screening\normals\mat\*RCC*.mat');

num_abs = length(abnormal_list);
num_norm = length(normal_list);

ab_size = ceil(num_abs / num_folds);
start_ab = (fold_id-1)*ab_size + 1;
end_ab = min(fold_id*ab_size, num_abs);

norm_size = ceil(num_norm / num_folds);
start_norm = (fold_id-1)*norm_size + 1;
end_norm = min(fold_id*norm_size, num_norm);

abs_idx = setdiff(1:num_abs, start_ab:end_ab);
norm_idx = setdiff(1:num_norm, start_norm:end_norm);

[abnormal_data] = sample_mammo_training_data(...
    'num_samples', 5e3,...
    'image_dir', 'C:\isbe\asymmetry_project\data\mammograms\2004_screening\abnormals\mat\',...
    'mask_dir', 'C:\isbe\asymmetry_project\data\masks\2004_screening\abnormals\',...
    'win_size', 3,...
    'num_levels', 4,...
    'feature_type', 'all',...
    'feature_shape', 'rect',...
    'rotate', 0,...
    'do_max', 0,...
    'image_list', abnormal_list(abs_idx));
[normal_data] = sample_mammo_training_data(...
    'num_samples', 5e3,...
    'image_dir', 'C:\isbe\asymmetry_project\data\mammograms\2004_screening\normals\mat\',...
    'mask_dir', 'C:\isbe\asymmetry_project\data\masks\2004_screening\normals\',...
    'win_size', 3,...
    'num_levels', 4,...
    'feature_type', 'all',...
    'feature_shape', 'rect',...
    'rotate', 0,...
    'do_max', 0,...
    'image_list', normal_list(norm_idx));
%%
[training_data training_labels] = sample_mammo_training_data(...
    'num_samples', 5e3,...
    'abnormal_dir', 'C:\isbe\asymmetry_project\data\mammograms\2004_screening\abnormals\mat\',...
    'normal_dir', 'C:\isbe\asymmetry_project\data\mammograms\2004_screening\normals\mat\',...
    'abnormal_mask_dir', 'C:\isbe\asymmetry_project\data\masks\2004_screening\abnormals\',...
    'normal_mask_dir', 'C:\isbe\asymmetry_project\data\masks\2004_screening\normals\',...
    'fold_id', 1,...
    'view', 'RCC',...
    'win_size', 3,...
    'num_levels', 4,...
    'feature_type', 'all',...
    'feature_shape', 'rect',...
    'rotate', 0,...
    'do_max', 0);