%% -----------------------------------------------------------------------
% Script testing whether RF prediction forests built in the old mammography
% asymmetry project work on log transformed digital mammograms
data_root = 'C:\isbe\density\xin\';
%%
%Load in the raw images and log transform
im = dicomread([data_root 'mammograms_raw\LMLO094931-20120510-RAW.dcm']);
mam_log = -log(double(im));

mam_mask = im < 2^13;
mam_log_min = min(mam_log(mam_mask));
mam_log_max = max(mam_log(mam_mask));
mam_8bit = 255*(mam_log - mam_log_min)/(mam_log_max - mam_log_min);
mam_8bit(~mam_mask) = 0;
figure; imgray(mam_8bit);
clear im mam_log;

mam_roi = mam_8bit(1258+(1:512), 284+(1:512));

save([data_root 'mammograms_log\LMLO094931-20120510-log.mat'], 'mam_8bit');
save([data_root 'breast_masks\LMLO094931-20120510-mast.mat'], 'mam_mask');
%% Try and orientation RF
load([data_root 'mammograms_log\LMLO094931-20120510-log.mat'], 'mam_8bit');
load([data_root 'breast_masks\LMLO094931-20120510-mast.mat'], 'mam_mask');

rf_ori = u_load([data_root 'rfs\orientation\286715\predictor.mat']);
rf_ori.tree_root = [data_root 'rfs\orientation\']; %RFs were created on hydra so need to change this
save([data_root 'rfs\orientation\286715\predictor.mat'], 'rf_ori');
ori_args = u_load([data_root 'rfs\orientation\286715\job_args.mat']);

[ori_prediction] = predict_image(...
    'image_in', imresize(mam_8bit, 0.5, 'lanczos2'),...
    'decomposition_args', ori_args.decomposition_args,...
    'predictor', rf_ori, ...
    'prediction_type', 'rf_regression',...
    'output_type', 'orientation',...
    'use_probs', 0,...
    'mask', imresize(mam_mask, 0.5),...
    'tree_mask', [], ...
    'num_trees', [], ...
    'max_size', 256,...
    'incremental_results', 0);
%Use complex2rgb to display orientation map, color (hue) corresponds to
%angle, brightness (saturation) corresponds to confidence in the prediction
figure; imgray(complex2rgb(ori_prediction)); 
%% Try a CLS detection RF
rf_line = u_load([data_root 'rfs\detection\358952\predictor.mat']);
rf_line.tree_root = [data_root 'rfs\detection\']; %RFs were created on hydra so need to change this
save([data_root 'rfs\detection\358952\predictor.mat'], 'rf_line');
line_args = u_load([data_root 'rfs\detection\358952\job_args.mat']);

[line_prediction] = predict_image(...
    'image_in', imresize(mam_8bit, 0.5, 'lanczos2'),...
    'decomposition_args', line_args.decomposition_args,...
    'predictor', rf_line, ...
    'prediction_type', 'rf_classification',...
    'output_type', 'detection',...
    'use_probs', 0,...
    'mask', imresize(mam_mask, 0.5),...
    'tree_mask', [], ...
    'num_trees', [], ...
    'max_size', 256,...
    'incremental_results', 0);
figure; imgray(line_prediction);
%% Run in batch mode for a set of images
%Predict image set runs by splitting the number of images to process into
%different jobs, and running running one of those sets.
% I.e. if you have 100 images in your image directory
% num_jobs = 1, task_id = 1: predicts all the images
% num_jobs = 2, task_id = 1: predicts the first 50 images
% num_jobs = 2, task_id = 2: predicts the first images 51 - 100
% num_jobs = 4, task_id = 3: predicts the first images 51-75
% etc.
% You need to make sure the tree root for the RF is correctly set for this
% to run
% If using masks (i.e. to reduce processing time so you don't waste
% time classifying the background), the number of masks in the folder must
% be the same number and in the same order as the images (lazy programming
% but does the job)
predict_image_set(...
    'task_id',			1, ...
    'num_jobs',			1, ...
    'model_name',       'predictor',...
    'model_root',		[data_root '\rfs\orientation\'], ...
    'model_id',         '286715\',...
    'image_root',       data_root,...
    'image_dir',        'mammograms_log\', ...
    'mask_dir',			'breast_masks', ...
    'max_size',			256);
%
predict_image_set(...
    'task_id',			1, ...
    'num_jobs',			1, ...
    'model_name',       'predictor',...
    'model_root',		[data_root '\rfs\detection\'], ...
    'model_id',         '358952\',...
    'image_root',       data_root,...
    'image_dir',        'mammograms_log\', ...
    'mask_dir',			'breast_masks', ...
    'max_size',			256);
%%