function [training_data training_labels] = sample_mammo_segment_data(varargin)
%SAMPLE_MAMMO_TRAINING_DATA *Insert a one line summary here*
%   [] = sample_mammo_training_data(varargin)
%
% SAMPLE_MAMMO_TRAINING_DATA uses the U_PACKARGS interface function
% and so arguments to the function may be passed as name-value pairs
% or as a struct with fields with corresponding names. The field names
% are defined as:
%
% Mandatory Arguments:
%
% Optional Arguments:
%
% Outputs:
%
% Example:
%
% Notes:
%
% See also:
%
% Created: 17-Aug-2010
% Author: Michael Berks 
% Email : michael.berks@postgrad.man.ac.uk 
% Phone : +44 (0)161 275 1241 
% Copyright: (C) University of Manchester 

% Unpack the arguments:
args = u_packargs(varargin,... % the user's input
    '0', ... % non-strict mode
    {'num_samples',... % the mandatory arguments
    'mammo_dir',...
    'mask_dir',...
    'num_mammos'}, ...
    'view', [],...
    'win_size', 1,...
    'num_levels', 5,...
    'feature_type', 'all',...
    'feature_shape', 'rect',...
    'rotate', 0,...
    'do_max', 0,...
    'image_type', '.mat',...
    'resize', 0.25,...
    'use_nag', 1,...
    'save_path', []);
clear varargin;

%First find all the abnormal mammograms that match the view type
mammo_list = dir([args.mammo_dir '*' args.view '*' args.image_type]);

%Select number of images to use
num_mammos = min(length(mammo_list), args.num_mammos);

[mammo_data] = sample_mammo_dt_data(...
    'num_samples', args.num_samples,...
    'image_dir', args.mammo_dir,...
    'mask_dir', args.mask_dir,...
    'win_size', args.win_size,...
    'num_levels', args.num_levels,...
    'feature_type', args.feature_type,...
    'feature_shape', args.feature_shape,...
    'rotate', args.rotate,...
    'do_max', args.do_max,...
    'image_list', mammo_list(1:num_mammos), ...
    'image_type', args.image_type,...
    'resize', args.resize,...
    'invert_mask', 0,...
    'use_nag', args.use_nag);
[background_data] = sample_mammo_dt_data(...
    'num_samples', args.num_samples,...
    'image_dir', args.mammo_dir,...
    'mask_dir', args.mask_dir,...
    'win_size', args.win_size,...
    'num_levels', args.num_levels,...
    'feature_type', args.feature_type,...
    'feature_shape', args.feature_shape,...
    'rotate', args.rotate,...
    'do_max', args.do_max,...
    'image_list', mammo_list(1:num_mammos), ...
    'image_type', args.image_type,...
    'resize', args.resize,...
    'invert_mask', 1,...
    'use_nag', args.use_nag);

training_data = [mammo_data; background_data];
training_labels = [true(args.num_samples,1); false(args.num_samples,1)];