function [] = density_read_VAS_forms()
%DENSITY_READ_VAS_FORMS implements a GUI to read VAS density forms from
%scanned forms
%   [] = density_read_VAS_forms()
%
% Inputs:
%
% Outputs:
%
% Example:
%
% Notes:
%
% See also:
%
% Created: 17-Jul-2009
% Author: Michael Berks 
% Email : michael.berks@postgrad.man.ac.uk 
% Phone : +44 (0)161 275 1241 
% Copyright: (C) University of Manchester

%Create the main figure;
main_fig = figure(...
    'Name', 'Read density VAS forms',...
    'WindowStyle', 'normal',...
    'MenuBar', 'none',...
    'NumberTitle', 'off',...
    'Position', [100 100 620 210]);

%Create the UI controls for the main fig
pdf_file_box = uicontrol(...
    'Style', 'edit',...
    'Position', [100 160 400 40],...
    'BackgroundColor', [1 1 1],...
    'Parent', main_fig,...
    'String', []);

pdf_file_select = uicontrol(...
    'Style', 'pushbutton',...
    'Position', [510 160 100 40],...
    'String', 'Select',...
    'Parent', main_fig,...
    'Callback', @pdf_file_select_Callback);%#ok

pdf_file_text = uicontrol(...
    'Style','text',...
    'BackgroundColor', get(main_fig, 'Color'),...
    'FontName', 'Arial',...
    'String', 'VAS .pdf file:',...
    'HorizontalAlignment', 'right',...
    'Position', [10 160 80 25]);%#ok

xls_file_box = uicontrol(...
    'Style', 'edit',...
    'Position', [100 110 400 40],...
    'BackgroundColor', [1 1 1],...
    'Parent', main_fig,...
    'String', []);

xls_file_select = uicontrol(...
    'Style', 'pushbutton',...
    'Position', [510 110 100 40],...
    'String', 'Select',...
    'Parent', main_fig,...
    'Callback', @xls_file_select_Callback);%#ok

xls_file_text = uicontrol(...
    'Style','text',...
    'BackgroundColor', get(main_fig, 'Color'),...
    'FontName', 'Arial',...
    'String', 'Results .xls file:',...
    'HorizontalAlignment', 'right',...
    'Position', [10 110 80 25]);%#ok

reader_initials_text = uicontrol(...
    'Style','text',...
    'BackgroundColor', get(main_fig, 'Color'),...
    'FontName', 'Arial',...
    'String', 'Reader initials:',...
    'HorizontalAlignment', 'right',...
    'Position', [10 60 80 25]);%#ok

reader_initials_box = uicontrol(...
    'Style', 'edit',...
    'Position', [100 60 50 40],...
    'BackgroundColor', [1 1 1],...
    'Parent', main_fig,...
    'String', []);

read_forms = uicontrol(...
    'Style', 'pushbutton',...
    'Position', [100 10 200 40],...
    'String', 'Read forms',...
    'Parent', main_fig,...
    'Callback', @read_forms_Callback);%#ok

% advanced_options = uicontrol(...
%     'Style', 'pushbutton',...
%     'Position', [310 10 100 40],...
%     'Parent', main_fig,...
%     'String', 'Advanced options');

%create args to be passed to form reader function
args = [];

%specify default locations for browser to open
try
    fid = fopen('C:\program files\density_software\default_locations.txt');
    def_txt = textscan(fid, '%s %s', 'delimiter', '=');
    fclose(fid);

    default_form_dir = ...
        def_txt{2}{strncmpi(def_txt{1}, 'pdf_scans_dir', length('pdf_scans_dir'))};
    default_xls_dir = ...
        def_txt{2}{strncmpi(def_txt{1}, 'xls_results_dir', length('xls_results_dir'))};
catch
    display('Problem opening default file locations');
    default_form_dir = '';
    default_xls_dir = '';
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Callbacks for UI controls
% --------------------------------------------------------------------
    function pdf_file_select_Callback(hObject, eventdata) %#ok
    % Callback to...
        [args.form_name, args.form_dir] = uigetfile('*.pdf',...
            'Select the form to process', default_form_dir);
        if args.form_name
            set(pdf_file_box, 'string', [args.form_dir, args.form_name]);
        end
    end
%--------------------------------------------------------------------------
    function xls_file_select_Callback(hObject, eventdata) %#ok
    % Callback to...
        [args.xls_name, args.xls_dir] = uigetfile('*.xls',...
            'Select an excel file for the results',default_xls_dir);
        if args.xls_name
            set(xls_file_box, 'string', [args.xls_dir, args.xls_name]);
        end
    end
%--------------------------------------------------------------------------
    function read_forms_Callback(hObject, eventdata) %#ok
    % Callback to...
        form_name = get(pdf_file_box, 'string');
        excel_name = get(xls_file_box, 'string');
        reader_initials = get(reader_initials_box, 'string');
        if isempty(form_name) || isempty(excel_name)
            warndlg('Please make sure have selected a PDF form to process, and an excel file for the results',...
                'Missing data');
        elseif isempty(reader_initials)
            warndlg('Please enter the initials of the reader for this batch of forms',...
                'Missing data');
        else
            
            set(get(main_fig, 'Children'), 'Enable', 'off');
            h = waitbar(0,'Reading forms. Please wait...');
            read_density_form_batch(form_name, [], excel_name, reader_initials, 0);
            close(h);
            answer = questdlg(...
                'Do you have more forms to process or would you like to exit?',...
                'Forms successfully read!','Continue', 'Exit', 'Exit');
            if strcmpi(answer, 'exit');
                close(main_fig);
            else
                set(get(main_fig, 'Children'), 'Enable', 'on');
            end            
        end
    end
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%---------------------- END OF FUNCTION -----------------------------------
%--------------------------------------------------------------------------
end
