function [] = density_create_VAS_forms()
%DENSITY_WRITE_VAS_FORMS implements a GUI to create VAS density forms
%   [] = density_write_VAS_forms()
%
% Inputs:
%
% Outputs:
%
% Example:
%
% Notes:
%
% See also:
%
% Created: 17-Jul-2009
% Author: Michael Berks 
% Email : michael.berks@postgrad.man.ac.uk 
% Phone : +44 (0)161 275 1241 
% Copyright: (C) University of Manchester

%Create the main figure;
main_fig = figure(...
    'Name', 'Create density VAS forms',...
    'WindowStyle', 'normal',...
    'MenuBar', 'none',...
    'NumberTitle', 'off',...
    'Position', [100 100 620 160]);

%Create the UI controls for the main fig
xls_file_box = uicontrol(...
    'Style', 'edit',...
    'Position', [100 110 400 40],...
    'BackgroundColor', [1 1 1],...
    'Parent', main_fig,...
    'String', []);

xls_file_select = uicontrol(... 
    'Style', 'pushbutton',...
    'Position', [510 110 100 40],...
    'String', 'Select',...
    'Parent', main_fig,...
    'Callback', @xls_file_select_Callback);%#ok

xls_file_text = uicontrol(... 
    'Style','text',...
    'BackgroundColor', get(main_fig, 'Color'),...
    'FontName', 'Arial',...
    'String', 'Data .xls file:',...
    'HorizontalAlignment', 'right',...
    'Position', [10 110 80 25]);%#ok

pdf_dir_box = uicontrol(...
    'Style', 'edit',...
    'Position', [100 60 400 40],...
    'BackgroundColor', [1 1 1],...
    'Parent', main_fig,...
    'String', []);

pdf_dir_select = uicontrol(... 
    'Style', 'pushbutton',...
    'Position', [510 60 100 40],...
    'String', 'Select',...
    'Parent', main_fig,...
    'Callback', @pdf_dir_select_Callback);%#ok

pdf_dir_text = uicontrol(... 
    'Style','text',...
    'BackgroundColor', get(main_fig, 'Color'),...
    'FontName', 'Arial',...
    'String', 'Forms directory:',...
    'HorizontalAlignment', 'right',...
    'Position', [10 60 80 25]);%#ok

pdf_dir_box = uicontrol(...
    'Style', 'edit',...
    'Position', [100 60 400 40],...
    'BackgroundColor', [1 1 1],...
    'Parent', main_fig,...
    'String', []);

create_forms = uicontrol(... 
    'Style', 'pushbutton',...
    'Position', [100 10 200 40],...
    'String', 'Create forms',...
    'Parent', main_fig,...
    'Callback', @create_forms_Callback);%#ok

% advanced_options = uicontrol(...
%     'Style', 'pushbutton',...
%     'Position', [310 10 100 40],...
%     'Parent', main_fig,...
%     'String', 'Advanced options');

%create args to be passed to form reader function
args = [];

%specify default locations for browser to open
try
    fid = fopen('C:\program files\density_software\default_locations.txt');
    def_txt = textscan(fid, '%s %s', 'delimiter', '=');
    fclose(fid);

    default_pdf_dir = ...
        def_txt{2}{strncmpi(def_txt{1}, 'pdf_forms_dir', length('pdf_forms_dir'))};
    default_xls_dir = ...
        def_txt{2}{strncmpi(def_txt{1}, 'xls_names_dir', length('xls_names_dir'))};

catch
    display('Problem opening default file locations');
    default_pdf_dir = '';
    default_xls_dir = '';
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Callbacks for UI controls
% --------------------------------------------------------------------
    function pdf_dir_select_Callback(hObject, eventdata) %#ok
    % Callback to...
        args.pdf_dir = ...
            uigetdir(default_pdf_dir, 'Select the directory to the save the forms to');
        if args.pdf_dir
            set(pdf_dir_box, 'string', args.pdf_dir);
        end
    end
%--------------------------------------------------------------------------
    function xls_file_select_Callback(hObject, eventdata) %#ok
    % Callback to...
        [args.xls_name, args.xls_dir] = uigetfile('*.xls',...
            'Select the excel file containing the patient data',default_xls_dir);
        if args.xls_name
            set(xls_file_box, 'string', [args.xls_dir, args.xls_name]);
        end
    end
%--------------------------------------------------------------------------
    function create_forms_Callback(hObject, eventdata) %#ok
    % Callback to...
        form_folder = [get(pdf_dir_box, 'string'), filesep];
        xls_file = get(xls_file_box, 'string');
        if isempty(xls_file)
            warndlg('Please select an excel file containing participant data',...
                'Missing data');
        else
            set(get(main_fig, 'Children'), 'Enable', 'off');
            h = waitbar(0,'Creating forms. Please wait...');
            make_form_pdf_batch(xls_file, form_folder);
            close(h);
            answer = questdlg(...
                'Do you have more forms to create or would you like to exit?',...
                'Forms successfully created!','Continue', 'Exit', 'Exit');
            if strcmpi(answer, 'exit');
                close(main_fig);
            else
                set(get(main_fig, 'Children'), 'Enable', 'on');
            end
        end
    end
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%---------------------- END OF FUNCTION -----------------------------------
%--------------------------------------------------------------------------
end
