% Cente orientation, RFs
%--------------------------------------------------------------------------

%G", w=1
DECOMP_TYPE="g2d" WIN_SIZE=1 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2d" WIN_SIZE=3 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=1 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2da" WIN_SIZE=1 NUM_ANGLES=6 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2da" WIN_SIZE=3 NUM_ANGLES=6 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2da" WIN_SIZE=1 NUM_ANGLES=6 ROTATE=1 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2da" WIN_SIZE=1 NUM_ANGLES=6 DO_MAX=1 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'8298'" qsub -V -hold_jid xxxx -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'8321'" qsub -V -hold_jid 8321 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'8328'" qsub -V -hold_jid 8328 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'8331'" qsub -V -hold_jid 8331 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'10035'" qsub -V -hold_jid 10035 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh

MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'8298'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -t 6 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'8321'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 8324 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'8328'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 8329 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'8331'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 8332 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'10035'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 10040 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh

DECOMP_TYPE="dt" WIN_SIZE=3 PROBABILITY_DIR="8331/" MAKE_RESAMPLING_MAPS=0.25 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 PROBABILITY_DIR="8331/" MAKE_RESAMPLING_MAPS=0.50 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 PROBABILITY_DIR="8331/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 PROBABILITY_DIR="8331/" MAKE_RESAMPLING_MAPS=1.00 OUTPUT_TYPE="centre_orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'9832'" qsub -V -hold_jid 9832 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'9976'" qsub -V -hold_jid 9976 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'9977'" qsub -V -hold_jid 9977 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'9978'" qsub -V -hold_jid 9978 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh

MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'9832'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9843 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'9976'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9979 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'9977'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9980 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/centre_orientation/rf_regression" MODEL_PATH="'9978'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9981 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh

% Cente detection, RFs
%--------------------------------------------------------------------------

%G", w=1
DECOMP_TYPE="g2d" WIN_SIZE=1 OUTPUT_TYPE="centre_detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2d" WIN_SIZE=3 OUTPUT_TYPE="centre_detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=1 OUTPUT_TYPE="centre_detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 OUTPUT_TYPE="centre_detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh


MODEL_ROOT="models/vessel/centre_detection/rf_classification" MODEL_PATH="'8663'" qsub -V -hold_jid 8663 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/centre_detection/rf_classification" MODEL_PATH="'8680'" qsub -V -hold_jid 8680 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/centre_detection/rf_classification" MODEL_PATH="'8683'" qsub -V -hold_jid 8683 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/centre_detection/rf_classification" MODEL_PATH="'8686'" qsub -V -hold_jid 8686 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh

MODEL_ROOT="models/vessel/centre_detection/rf_classification" MODEL_PATH="'8663'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 8665 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/centre_detection/rf_classification" MODEL_PATH="'8680'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 8681 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/centre_detection/rf_classification" MODEL_PATH="'8683'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 8684 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/centre_detection/rf_classification" MODEL_PATH="'8686'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 8687 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh

MODEL_PATH="'8663'" OUTPUT_TYPE="centre_detection" PREDICTION_TYPE="rf_classification" IMAGE_ROOT="retinograms/DRIVE/training" FOV_MASK_DIR="fov_masks" ERROR_RATIO=0.5 qsub -V -l short matlab_code/trunk/hydra/cuc/make_sampling_maps_set.sh
MODEL_PATH="'8680'" OUTPUT_TYPE="centre_detection" PREDICTION_TYPE="rf_classification" IMAGE_ROOT="retinograms/DRIVE/training" FOV_MASK_DIR="fov_masks" ERROR_RATIO=0.5 qsub -V -l short matlab_code/trunk/hydra/cuc/make_sampling_maps_set.sh
MODEL_PATH="'8683'" OUTPUT_TYPE="centre_detection" PREDICTION_TYPE="rf_classification" IMAGE_ROOT="retinograms/DRIVE/training" FOV_MASK_DIR="fov_masks" ERROR_RATIO=0.5 qsub -V -l short matlab_code/trunk/hydra/cuc/make_sampling_maps_set.sh
MODEL_PATH="'8686'" OUTPUT_TYPE="centre_detection" PREDICTION_TYPE="rf_classification" IMAGE_ROOT="retinograms/DRIVE/training" FOV_MASK_DIR="fov_masks" ERROR_RATIO=0.5 qsub -V -l short matlab_code/trunk/hydra/cuc/make_sampling_maps_set.sh

%--------------------------------------------------------------------------
%
% Whole vessel detection, RFs
%--------------------------------------------------------------------------
DECOMP_TYPE="g2d" WIN_SIZE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2d" WIN_SIZE=3 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8892'" qsub -V -hold_jid 8892 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8893'" qsub -V -hold_jid 8893 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8894'" qsub -V -hold_jid 8894 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8895'" qsub -V -hold_jid 8895 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh

MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8892'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 8896 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8893'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 8897 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8894'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 8898 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8895'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 8899 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh

DECOMP_TYPE="g2d" WIN_SIZE=1 PROBABILITY_DIR="8892/" MAKE_RESAMPLING_MAPS=0.25 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2d" WIN_SIZE=3 PROBABILITY_DIR="8893/" MAKE_RESAMPLING_MAPS=0.25  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=1 PROBABILITY_DIR="8894/" MAKE_RESAMPLING_MAPS=0.25  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 PROBABILITY_DIR="8895/" MAKE_RESAMPLING_MAPS=0.25  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="g2d" WIN_SIZE=1 PROBABILITY_DIR="8892/" MAKE_RESAMPLING_MAPS=0.5 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2d" WIN_SIZE=3 PROBABILITY_DIR="8893/" MAKE_RESAMPLING_MAPS=0.5  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=1 PROBABILITY_DIR="8894/" MAKE_RESAMPLING_MAPS=0.5  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 PROBABILITY_DIR="8895/" MAKE_RESAMPLING_MAPS=0.5  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="g2d" WIN_SIZE=1 PROBABILITY_DIR="8892/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2d" WIN_SIZE=3 PROBABILITY_DIR="8893/" MAKE_RESAMPLING_MAPS=0.75  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=1 PROBABILITY_DIR="8894/" MAKE_RESAMPLING_MAPS=0.75  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 PROBABILITY_DIR="8895/" MAKE_RESAMPLING_MAPS=0.75  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="g2d" WIN_SIZE=1 PROBABILITY_DIR="8892/" MAKE_RESAMPLING_MAPS=1.00 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2d" WIN_SIZE=3 PROBABILITY_DIR="8893/" MAKE_RESAMPLING_MAPS=1.00  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=1 PROBABILITY_DIR="8894/" MAKE_RESAMPLING_MAPS=1.00  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 PROBABILITY_DIR="8895/" MAKE_RESAMPLING_MAPS=1.00  OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="g12d" WIN_SIZE=3 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="mono" WIN_SIZE=3 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="linop" WIN_SIZE=3 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="haar" WIN_SIZE=3 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2dg" WIN_SIZE=3 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gaborg" WIN_SIZE=3 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g1d" WIN_SIZE=3 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2di" WIN_SIZE=3 SIGMA_RANGE="[1 5]" OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabori" WIN_SIZE=3 SIGMA_RANGE="[1 5]" OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2da" WIN_SIZE=3 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="dt" WIN_SIZE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2d" WIN_SIZE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g12d" WIN_SIZE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="mono" WIN_SIZE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="linop" WIN_SIZE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="haar" WIN_SIZE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g1d" WIN_SIZE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2di" WIN_SIZE=1 SIGMA_RANGE="[1 5]" OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabori" WIN_SIZE=1 SIGMA_RANGE="[1 5]" OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="g12d" WIN_SIZE=3 PROBABILITY_DIR="11476/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="mono" WIN_SIZE=3 PROBABILITY_DIR="11477/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="linop" WIN_SIZE=3 PROBABILITY_DIR="11478/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="haar" WIN_SIZE=3 PROBABILITY_DIR="11479/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 PROBABILITY_DIR="24066/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2di" WIN_SIZE=3 SIGMA_RANGE="[1 5]" PROBABILITY_DIR="38797/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabori" WIN_SIZE=3 SIGMA_RANGE="[1 5]" PROBABILITY_DIR="38798/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 SIGMA_RANGE="[1:16]" NUM_ANGLES=9 PROBABILITY_DIR="24066/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 SIGMA_RANGE="[1 2 4 8 16]" NUM_ANGLES=18 PROBABILITY_DIR="24066/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="g2da" WIN_SIZE=1 NUM_ANGLES=6 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2da" WIN_SIZE=3 NUM_ANGLES=6 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2da" WIN_SIZE=1 NUM_ANGLES=6 ROTATE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2da" WIN_SIZE=1 NUM_ANGLES=6 DO_MAX=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2da" WIN_SIZE=3 NUM_ANGLES=6 ROTATE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2da" WIN_SIZE=3 NUM_ANGLES=6 DO_MAX=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="gabor" WIN_SIZE=1 NUM_ANGLES=6 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 NUM_ANGLES=6 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=1 NUM_ANGLES=6 ROTATE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=1 NUM_ANGLES=6 DO_MAX=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 NUM_ANGLES=6 ROTATE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 NUM_ANGLES=6 DO_MAX=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="dt" WIN_SIZE=3 ROTATE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 DO_MAX=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="dt" WIN_SIZE=3 ROTATE=2 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="dt" WIN_SIZE=3 DO_MAX=2 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="gabor" WIN_SIZE=3 NUM_ANGLES=6 SIGMA_RANGE=1 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 NUM_ANGLES=6 SIGMA_RANGE=2 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 NUM_ANGLES=6 SIGMA_RANGE=4 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 NUM_ANGLES=6 SIGMA_RANGE=8 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 NUM_ANGLES=6 SIGMA_RANGE=16 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="g2d" WIN_SIZE=5 OUTPUT_TYPE="detection" PREDICTION_TYPE="rf_classification" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9151'" qsub -V -hold_jid 9151 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9152'" qsub -V -hold_jid 9152 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9153'" qsub -V -hold_jid 9153 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9154'" qsub -V -hold_jid 9154 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9155'" qsub -V -hold_jid 9155 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9156'" qsub -V -hold_jid 9156 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9157'" qsub -V -hold_jid 9157 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9158'" qsub -V -hold_jid 9158 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9159'" qsub -V -hold_jid 9159 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9160'" qsub -V -hold_jid 9160 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9161'" qsub -V -hold_jid 9161 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9162'" qsub -V -hold_jid 9162 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9473'" qsub -V -hold_jid 9473 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9474'" qsub -V -hold_jid 9474 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9475'" qsub -V -hold_jid 9475 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9476'" qsub -V -hold_jid 9476 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'11476'" qsub -V -hold_jid 11476 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'11477'" qsub -V -hold_jid 11477 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'11478'" qsub -V -hold_jid 11478 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'11479'" qsub -V -hold_jid 11479 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'11480'" qsub -V -hold_jid 11480 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12393'" qsub -V -hold_jid 12393 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12394'" qsub -V -hold_jid 12394 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12395'" qsub -V -hold_jid 12395 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12396'" qsub -V -hold_jid 12396 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12397'" qsub -V -hold_jid 12397 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12595'" qsub -V -hold_jid 12595 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12787'" qsub -V -hold_jid 12787 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13508'" qsub -V -hold_jid 13508 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13509'" qsub -V -hold_jid 13509 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13569'" qsub -V -hold_jid 13569 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13570'" qsub -V -hold_jid 13570 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13571'" qsub -V -hold_jid 13571 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13572'" qsub -V -hold_jid 13572 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14285'" qsub -V -hold_jid 14285 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14286'" qsub -V -hold_jid 14286 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14287'" qsub -V -hold_jid 14287 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14288'" qsub -V -hold_jid 14288 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14289'" qsub -V -hold_jid 14289 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14290'" qsub -V -hold_jid 14290 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14971'" qsub -V -hold_jid 14971 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24066'" qsub -V -hold_jid 24066 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24072'" qsub -V -hold_jid 24072 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24221'" qsub -V -hold_jid 24221 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24222'" qsub -V -hold_jid 24222 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24303'" qsub -V -hold_jid 24303 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24336'" qsub -V -hold_jid 24336 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24820'" qsub -V -hold_jid 24820 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'33429'" qsub -V -hold_jid 33429 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'33430'" qsub -V -hold_jid 33430 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'34015'" qsub -V -hold_jid 34015 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'34016'" qsub -V -hold_jid 34016 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'34237'" qsub -V -hold_jid 34237 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'38797'" qsub -V -hold_jid 38797 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'38798'" qsub -V -hold_jid 38798 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42288'" qsub -V -hold_jid 42288 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42289'" qsub -V -hold_jid 42289 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42290'" qsub -V -hold_jid 42290 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42291'" qsub -V -hold_jid 42291 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42292'" qsub -V -hold_jid 42292 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42293'" qsub -V -hold_jid 42293 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42294'" qsub -V -hold_jid 42294 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42295'" qsub -V -hold_jid 42295 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42381'" qsub -V -hold_jid 42381 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42382'" qsub -V -hold_jid 42382 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'50981'" qsub -V -hold_jid 50981 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'51417'" qsub -V -hold_jid 51417 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh

MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9151'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9165 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9152'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9166 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9153'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9167 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9154'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9168 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9155'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9169 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9156'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9170 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9157'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9171 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9158'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9172 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9159'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9173 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9160'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9174 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9161'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9175 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9162'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9176 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9473'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9477 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9474'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9478 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9475'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9479 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9476'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 9480 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'11476'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 11481 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'11477'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 11482 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'11478'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 11483 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'11479'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 11484 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'11480'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 11485 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12393'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12398 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12394'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12399 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12395'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12400 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12396'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12401 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12397'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12402 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12595'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12787'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12815 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13508'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 13515 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13509'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 13516 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13569'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 13573 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13570'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 13574 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13571'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 13575 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'13572'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 13576 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14285'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 14291 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14286'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 14292 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14287'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 14293 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14288'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 14294 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14289'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 14295 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14290'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 14296 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'14971'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 14972 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24066'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24067 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24072'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24073 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24221'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24223 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24222'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24224 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24303'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24304 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24336'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24337 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24820'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24821 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'33429'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 33431 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'33430'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 33432 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'34015'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 34017 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'34016'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 34018 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'34237'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 34238 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'38797'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 38800 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'38798'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 38801 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh

MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9159'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9160'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9161'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'9162'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh

MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8892'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8893'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8894'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'8895'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh

MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12393'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'12394'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'24303'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42381'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -hold_jid 42383 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'42382'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -hold_jid 42384 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'50981'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -hold_jid 50982 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/detection/rf_classification" MODEL_PATH="'51417'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -hold_jid 51418 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh

%--------------------------------------------------------------------------
%Whole vessel orientation
DECOMP_TYPE="dt" WIN_SIZE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2d" WIN_SIZE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g12d" WIN_SIZE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="mono" WIN_SIZE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="linop" WIN_SIZE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="haar" WIN_SIZE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g1d" WIN_SIZE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2di" WIN_SIZE=3 SIGMA_RANGE="[1 5]" OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabori" WIN_SIZE=3 SIGMA_RANGE="[1 5]" OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2da" WIN_SIZE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 SIGMA_RANGE=1 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 SIGMA_RANGE=2 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 SIGMA_RANGE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 SIGMA_RANGE=4 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 SIGMA_RANGE=5 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="dt" WIN_SIZE=1 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2d" WIN_SIZE=1 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g12d" WIN_SIZE=1 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="mono" WIN_SIZE=1 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="linop" WIN_SIZE=1 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="haar" WIN_SIZE=1 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=1 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g1d" WIN_SIZE=1 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2di" WIN_SIZE=1 SIGMA_RANGE="[1 5]" OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabori" WIN_SIZE=1 SIGMA_RANGE="[1 5]" OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

DECOMP_TYPE="g2d" WIN_SIZE=3 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12242'" qsub -V -hold_jid 12242 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12243'" qsub -V -hold_jid 12243 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12244'" qsub -V -hold_jid 12244 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12245'" qsub -V -hold_jid 12245 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12246'" qsub -V -hold_jid 12246 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12247'" qsub -V -hold_jid 12247 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12248'" qsub -V -hold_jid 12248 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24069'" qsub -V -hold_jid 24069 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24293'" qsub -V -hold_jid 24293 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24294'" qsub -V -hold_jid 24294 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24342'" qsub -V -hold_jid 24342 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24824'" qsub -V -hold_jid 24824 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'30469'" qsub -V -hold_jid 30469 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'30470'" qsub -V -hold_jid 30470 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'30471'" qsub -V -hold_jid 30471 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'30472'" qsub -V -hold_jid 30472 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'30473'" qsub -V -hold_jid 30473 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38788'" qsub -V -hold_jid 38788 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38789'" qsub -V -hold_jid 38789 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38809'" qsub -V -hold_jid 38809 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38810'" qsub -V -hold_jid 38810 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38811'" qsub -V -hold_jid 38811 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38812'" qsub -V -hold_jid 38812 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38813'" qsub -V -hold_jid 38813 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38814'" qsub -V -hold_jid 38814 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38815'" qsub -V -hold_jid 38815 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38816'" qsub -V -hold_jid 38816 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38817'" qsub -V -hold_jid 38817 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38818'" qsub -V -hold_jid 38818 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh

MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12242'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12250 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12243'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12251 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12244'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12252 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12245'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12253 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12246'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12254 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12247'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12255 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'12248'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 12256 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24069'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24070 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24293'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24296 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24294'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24297 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24342'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24345 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24824'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 24826 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'30469'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 30474 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'30470'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 30475 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'30471'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 30476 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'30472'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 30477 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'30473'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 30478 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38788'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 38805 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'38789'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/training" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=1 qsub -V -hold_jid 38806 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
 

DECOMP_TYPE="dt" WIN_SIZE=3 PROBABILITY_DIR="12242/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2d" WIN_SIZE=3 PROBABILITY_DIR="12243/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g12d" WIN_SIZE=3 PROBABILITY_DIR="12244/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="mono" WIN_SIZE=3 PROBABILITY_DIR="12245/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="linop" WIN_SIZE=3 PROBABILITY_DIR="12246/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="haar" WIN_SIZE=3 PROBABILITY_DIR="12247/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabor" WIN_SIZE=3 PROBABILITY_DIR="24069/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="g2di" WIN_SIZE=3 SIGMA_RANGE="[1 5]" PROBABILITY_DIR="38788/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh
DECOMP_TYPE="gabori" WIN_SIZE=3 SIGMA_RANGE="[1 5]" PROBABILITY_DIR="38789/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=10 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=100000 MODEL_ROOT="models/vessel" qsub -V -l twoday -t 1-20 matlab_code/trunk/hydra/cuc/build_predictor.sh

MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13292'" qsub -V -hold_jid 13292 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13293'" qsub -V -hold_jid 13293 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13294'" qsub -V -hold_jid 13294 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13295'" qsub -V -hold_jid 13295 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13296'" qsub -V -hold_jid 13296 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13297'" qsub -V -hold_jid 13297 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13298'" qsub -V -hold_jid 13298 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24308'" qsub -V -hold_jid 24308 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'42373'" qsub -V -hold_jid 42373 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'42374'" qsub -V -hold_jid 42374 -l short matlab_code/trunk/hydra/cuc/combine_hydra_rfs.sh

MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13592'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13593'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13594'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'13595'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'24308'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'42373'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -hold_jid 42375 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh
MODEL_ROOT="models/vessel/orientation/rf_regression" MODEL_PATH="'42374'" NUM_JOBS=10 IMAGE_ROOT="retinograms/DRIVE/test" MASK_DIR="fov_masks" USE_SAMPLED_MAPS=0 qsub -V -hold_jid 42376 -t 1-10 -l twoday matlab_code/trunk/hydra/cuc/predict_image_set.sh

%%
%Test stuff
DECOMP_TYPE="g2d" WIN_SIZE=3 PROBABILITY_DIR="12243/" MAKE_RESAMPLING_MAPS=0.75 OUTPUT_TYPE="orientation" PREDICTION_TYPE="rf_regression" NUM_TREES=1 IMAGE_TYPE="real" IMAGE_ROOT="retinograms/DRIVE/training" NUM_SAMPLES=1000 MODEL_ROOT="models/vessel" qsub -V -l short -t 1 matlab_code/trunk/hydra/cuc/build_predictor.sh
