addpath(genpath('S:\projects\mammography\matlab\'));

[tr_data,tr_labels,parameters] = ...
	generate_line_training_data(...
		'num_samples', 10,...
		'bg_dir', 'U:\projects\mammography\data\synthetic_backgrounds\smooth512\train\',...
		'bg_fmt', 'png',...
		'save_path', 'U:\projects\mammography\data\training\detection\dtcwt\',...
		'detection_type', 'detection',...
		'decomp_type', 'dt',...
		'win_size', 1,...
		'plot', 0);
	



