function [args] = default_args(varargin)
% Function that returns a complete set of arguments for easy testing of
% modules.

args = u_packargs(varargin,... % the user's input
    '0', ... % non-strict mode
    'task_id',				unixenv('SGE_TASK_ID',1), ...
    'job_id',				unixenv('JOB_ID',['pc',datestr(now,'yyyymmddTHHMMSS')]), ...
    .... % What we want to predict, by what method, and using what input features
    'dataset',              unixenv('DATASET','drive'), ...
    'output_type',          unixenv('OUTPUT_TYPE', 'orientation'), ...
    'prediction_type',		unixenv('PREDICTION_TYPE','linear_regression'), ...
    'decomp_type', 			unixenv('DECOMP_TYPE','dt'), ...
    'image_type', 			unixenv('IMAGE_TYPE','line'), ...
    ... % Folders
    'image_root',           unixenv('IMAGE_ROOT', [asymmetryroot,'data/retinograms/DRIVE/training']),...
    'image_dir',            unixenv('IMAGE_DIR', 'images_extended'),...
    'fov_mask_dir',         unixenv('FOV_MASK_DIR', 'foveal_masks'),...
    'fg_mask_dir',          unixenv('FG_MASK_DIR', 'vessel_masks'),...
    'class_dir',            unixenv('CLASS_DIR', []),...
    'ori_dir',              unixenv('ORI_DIR', 'orientations'),...
    'width_dir',            unixenv('WIDTH_DIR', 'width_maps'), ...
    'model_dir',            unixenv('MODEL_DIR', [asymmetryroot,'data/models/']), ...
	... % Sampling parameters
    'num_samples',			unixenv('NUM_SAMPLES',2e4), ...
    'pts_per_image',		unixenv('PTS_PER_IMAGE',500), ...
    'sampling_method',      unixenv('SAMPLING_METHOD','generate_training_data'), ...
    'rgb_channel',          unixenv('RGB_CHANNEL','rgb'), ...
    'normalise', 			unixenv('NORMALISE',0), ...
    'shrink_fov',           unixenv('SHRINK_FOV',false), ...
    'bg_ratio',				unixenv('BG_RATIO',1), ...
    ... % Image synthesis parameters
    'bg_stem',				unixenv('BG_STEM','bg'), ...
    'num_bgs',				unixenv('NUM_BGS',100), ...
    'bg_zeros',				unixenv('BG_ZEROS',5), ...
    'bg_dir',				unixenv('BG_DIR','synthetic_backgrounds/real512/train/'), ...
	'bg_fmt',				unixenv('BG_FMT','mat'), ...
    'bg_mask_dir',          unixenv('MASK_DIR',[]), ...
    'orientation_range', 	unixenv('ORIENTATION_RANGE',[0 180]), ...
    'width_range', 			unixenv('WIDTH_RANGE',[4 16]), ...
    'contrast_range',       unixenv('CONTRAST_RANGE',[4 8]), ...
    'decay_rate', 			unixenv('DECAY_RATE',4), ...
    'line_type',			unixenv('BAR_TYPE','sin'), ...
    ... % Training data parameters
	'save_training_data',	unixenv('SAVE_TRAINING_DATA',false), ...
	'training_data_dir', 	unixenv('TRAINING_DATA_DIR','saved_training_data'), ...
	'training_data',		unixenv('TRAINING_DATA',''), ...
	... % Image feature/decomposition parameters
    'num_levels', 			unixenv('NUM_LEVELS',1), ...
    'win_size',				unixenv('WIN_SIZE',3), ...
    'do_max',				unixenv('DO_MAX',false), ...
    'rotate',				unixenv('ROTATE',false), ...
    'pca_filename',         unixenv('PCA_FILENAME',[]), ...
    'pca',                  unixenv('PCA',[]), ...
    ... % DTCWT parameters
    'feature_shape', 		unixenv('FEATURE_SHAPE','rect'), ...
    'feature_type',			unixenv('FEATURE_TYPE','conj'), ...
    ... % Gaussian derivative parameters
    'sigma_range', 			unixenv('SIGMA_RANGE',[1,2,4,8]), ...
    ... % LinOp parameters
    'num_angles', 			unixenv('NUM_ANGLES',8), ...
    ... % Monogenic parameters
    'min_wavelength',		unixenv('MIN_WAVELENGTH',4), ...
    'onf',					unixenv('ONF',0.65), ...
    ... % Tree/Forest parameters
    'n_trees',				unixenv('NUM_TREES',2), ...
    'split_criterion',      unixenv('SPLIT_CRITERION','gdi'),...
    'var_criterion',		unixenv('VAR_CRITERION','mabs'),...
    'split_min',			unixenv('SPLIT_MIN',10), ...
    'end_cut_min',			unixenv('END_CUT_MIN',1), ...
    'do_ubound',			unixenv('DO_UBOUND',1), ...
    'do_circular',			unixenv('DO_CIRCULAR',[]), ...
	'w_prior',				unixenv('W_PRIOR',0), ...
    'impure_thresh',		unixenv('IMPURE_THRESH',1e-4), ...
	'minimise_size',		unixenv('MINIMIZE_TREE',0), ...
    'd',                    unixenv('d',[]), ...
    ... % Miscellaneous parameters
    'overwrite',			unixenv('OVERWRITE',false), ...
    'use_nag',				unixenv('USE_NAG',false),...
    'rand_seed',			unixenv('RAND_SEED',[]) ...
);
