function [] = segment_breast_gui(varargin)
%STEPWEDGE_GUI *Insert a one line summary here*
%   [] = stepwedge_gui()
%
% Inputs:
%
% Outputs:
%
% Example:
%
% Notes:
%
% See also:
%
% Created: 25-Oct-2010
% Author: Michael Berks 
% Email : michael.berks@manchester.ac.uk 
% Phone : +44 (0)161 275 7669 
% Copyright: (C) University of Manchester 

%create args to be passed to form reader function
args = u_packargs(varargin, 0, ...
            'MammoNames', [],...
            'ResizeFactor', 0.176, ...
            'DebugMode', 0, ...
            'ThicknessMethod', 1, ...
            'TaperMethod', 1, ...
            'MaxPairs', [],...
            'DoNipple', 0,...
            'DoAnodeHeel', 0,...
            'GenerateTextResults', 0,...
            'StepHeights', [],...
            'NotchIdx',[],...
            'NumBits', 12,...
            'ImageFormat', 'tif',...
            'User', [] ...
			);
clear varargin;

%specify default locations for browser to open
try
    fid = fopen('default_locations.txt');
    def_txt = textscan(fid, '%s %s', 'delimiter', '=');
    fclose(fid);

    args.MammoDir = ...
        def_txt{2}{strncmpi(def_txt{1}, 'mammogram_dir', length('mammogram_dir'))};
    args.SegmentationDir = ...
        def_txt{2}{strncmpi(def_txt{1}, 'segmentation_dir', length('segmentation_dir'))};

catch last_err
    display(last_err);
    display('Problem opening default file locations');
    args.MammoDir = '';
    args.SegmentationDir = '';
end

%Create the main figure;
main_fig = figure(...
    'Name', 'Stepwedge density software',...
    'WindowStyle', 'normal',...
    'MenuBar', 'none',...
    'NumberTitle', 'off',...
    'Position', [100 100 640 160]);

%Create the UI controls for the main fig
mammograms_box = uicontrol(...
    'Style', 'edit',...
    'Position', [120 110 400 40],...
    'BackgroundColor', [1 1 1],...
    'Parent', main_fig,...
    'String', args.MammoDir);

mammograms_select = uicontrol(...
    'Style', 'pushbutton',...
    'Position', [530 110 100 40],...
    'String', 'Select',...
    'Parent', main_fig,...
    'Callback', @mammogram_select_Callback);%#ok

mammograms_text = uicontrol(...
    'Style','text',...
    'BackgroundColor', get(main_fig, 'Color'),...
    'FontName', 'Arial',...
    'String', 'Mammograms dir:',...
    'HorizontalAlignment', 'right',...
    'Position', [10 110 100 25]);%#ok

segmentation_dir_box = uicontrol(...
    'Style', 'edit',...
    'Position', [120 60 400 40],...
    'BackgroundColor', [1 1 1],...
    'Parent', main_fig,...
    'String', args.SegmentationDir);

segmentation_dir_select = uicontrol(... 
    'Style', 'pushbutton',...
    'Position', [530 60 100 40],...
    'String', 'Select',...
    'Parent', main_fig,...
    'Callback', @segmentation_select_Callback);%#ok

segmentation_dir_text = uicontrol(... 
    'Style','text',...
    'BackgroundColor', get(main_fig, 'Color'),...
    'FontName', 'Arial',...
    'String', 'Segmentation dir:',...
    'HorizontalAlignment', 'right',...
    'Position', [10 60 100 25]); %#ok

start_processing = uicontrol(...
    'Style', 'pushbutton',...
    'Position', [100 10 200 40],...
    'String', 'Start processing',...
    'Parent', main_fig,...
    'Callback', @start_processing_Callback);%#ok

% advanced_options = uicontrol(...
%     'Style', 'pushbutton',...
%     'Position', [310 10 100 40],...
%     'Parent', main_fig,...
%     'String', 'Advanced options');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Callbacks for UI controls
%--------------------------------------------------------------------------
    function mammogram_select_Callback(hObject, eventdata) %#ok
    % Callback to...
        [mammo_names mammo_dir] = ...
            uigetfile([args.MammoDir '\*.' args.ImageFormat], 'Select the mammograms to process','Multiselect','on');
        if ~isnumeric(mammo_names)
            if iscell(mammo_names)
                num_mammos = [num2str(length(mammo_names)) ' mammograms'];
            else
                num_mammos = '1 mammogram';
            end
            mammo_str = ['... (' num_mammos ' selected)'];
            
            set(mammograms_box, 'string', [mammo_dir mammo_str]);
            args.MammoNames = mammo_names;
            args.MammoDir = mammo_dir;
        end
    end
% --------------------------------------------------------------------
    function segmentation_select_Callback(hObject, eventdata) %#ok
    % Callback to...
        segmentation_dir = ...
            uigetdir(args.SegmentationDir, 'Select the directory containing breast segmentations');
        if ~isnumeric(segmentation_dir)
            set(segmentation_dir_box, 'string', segmentation_dir);
            args.SegmentationDir = segmentation_dir;
        end
    end 
%--------------------------------------------------------------------------
    function start_processing_Callback(hObject, eventdata) %#ok
    % Callback to...
        if isempty(args.MammoNames)
            warndlg('Please select 1 or more mammograms to continue',...
                'No mammograms selected');
        else
            num_mammos = length(args.MammoNames);
            dlg = warndlg({['Processing ' num2str(num_mammos) ' image(s)'];...
                    'May take several minutes'},...
                    'Segmenting images');
                
            [failed_list] = segment_breast_batch(args.MammoDir, args.SegmentationDir, [], args.MammoNames, 0, 0);          
            close(dlg);
            
            results_file = [args.SegmentationDir '\segmentation_results.txt'];
            
            if ~isempty(failed_list)
   
                warndlg({[num2str(length(failed_list)) ' image(s) failed to process correctly.'];...
                    ['See ' results_file ' for a list of failed images.']},...
                    'Some segmentations failed');
            else
                warndlg('All images successfully processed',...
                    'Segmenting images');
            end
        end
    end
%--------------------------------------------------------------------------
%--------------------------------------------------------------------------
%---------------------- END OF FUNCTION -----------------------------------
%--------------------------------------------------------------------------
end

