function [breast_border breast_air pectoral_edge nipple] = segment_breast_resize(new_size, segmentation)
%SEGMENT_BREAST_RESIZE resizes a segmented breast border to match a given
%set of dimensions
%   [breast_border] = segment_breast_resize(new_size,segmentation)
%
% Inputs:
%      new_size- the dimensions of the mammogram to which the new border is
%      resized
%
%      segmentation- structure as generated by SEGMENT_BREAST
%
%
% Outputs:
%      breast_border- Nx2 array of (x,y) co-ordinates for the resized
%      breast border
%      pectoral_edge
%      nipple
%
%
% Example:
%
% Notes:
%
% See also: SEGMENT_BREAST
%
% Created: 25-Aug-2009
% Author: Michael Berks 
% Email : michael.berks@postgrad.man.ac.uk 
% Phone : +44 (0)161 275 1241 
% Copyright: (C) University of Manchester

%Perform a test hear to check the aspect ratio of the new size is the same
%as that in the segmentation
sf_r = new_size(1) / segmentation.size(1);
sf_c = new_size(2) / segmentation.size(2);

if abs(sf_r - sf_c) > .01
    display('Warning: aspect ratios of a new and old size do not match. Are you sure this is the correct segmentation?');
end

%Scale the breast border, subtracting 1 first so coordinates have origin at
%(0,0), then add 1 to finish
breast_border = sf_r * (segmentation.breast_border - 1) + 1;
breast_air = segmentation.breast_air;

if nargout > 2 && isfield(segmentation, 'pectoral_edge') 
    pectoral_edge = sf_r * (segmentation.pectoral_edge - 1) + 1;
else
    pectoral_edge = [];
end
if nargout > 2 && isfield(segmentation, 'nipple') && ~isempty(segmentation.nipple)
    nipple = sf_r * (segmentation.nipple - 1) + 1;
else
    nipple = [];
end
    

