function [y_fit proximities] = mb_random_forest_reg_predict_boot(forest, X)
%MB_RANDOM_FOREST_CLASS_PREDICT given a random forest and input data,
%predict the set of class labels for the data
%   [random_forest] = mb_random_forest_class_predict(forest, X)
%
%   X:      N x d matrix of input data, where each row is a
%           datapoint consisting of d input variables
%
%   forest: Random forest structure as generated by
%   MB_RANDOM_FOREST_CLASS_TRAIN
%
% Outputs:
%   y_fit:  Set of class labels predicted for each data point (note these
%           are currently returned as text labels in an Nx1 cell string
%           array. To convert to numeric values call str2double(y_fit),
%           which will produce an Nx1 vector of equivalent numeric values
%
%   votes:  Votes for each class for each data point (note by dividing by
%           the number of trees in the forest these can be used to
%           constructed output probabilities (as opposed to hard labels)
%
% Example:
%
% Notes:
%
% See also: MB_RANDOM_FOREST_REG_TRAIN_BOOT MB_TREE_PREDICT
%
% Created: 13-Oct-2009
% Author: Michael Berks 
% Email : michael.berks@postgrad.man.ac.uk 
% Phone : +44 (0)161 275 1241 
% Copyright: (C) University of Manchester 

%workout number of data points and input variables
N = size(X, 1);

%Work out number of trees in forest and number of output classes
ntrees = length(forest.trees);
    
%pre-allocate space for predictions from each tree
y_sum = zeros(N, 1);

if nargout > 2
    proximities = zeros(N);
end
%Loop through trees get prediction for each data point
for ii = 1:ntrees

    %Get predictions for data from this tree and add to running sum
    [y_tree nodes] = mb_tree_predict(forest.trees{ii}, X);
    y_sum = y_sum + y_tree;
    
    if nargout > 1
    %Compute proximity measure - i.e. count the number of times data points
    %end up at the same leaf node
        leaf_nodes = unique(nodes);
        for jj = 1:length(leaf_nodes)
            leaf = leaf_nodes(jj);
            leaf_pts = double(nodes == leaf);
            proximities = proximities + (leaf_pts * leaf_pts');
        end
    end   
end

%Divide by number trees to get final regression values
y_fit = y_sum / ntrees;

%If we need to calculate proximities, divide by ntrees to get measure
%between 0 and 1
if nargout > 2
    proximities = proximities / ntrees;
end